board_topic:
    channel: board/{id}
    handler:
        callback: 'board.topic'
    requirements:
        id:
            pattern: "[a-zA-Z0-9-]+"

board_workspace_topic:
    channel: board/workspace/{id}
    handler:
        callback: 'board_workspace.topic'
    requirements:
        id:
            pattern: "[a-zA-Z0-9-]+"