driveupload_upload:
  path:       /upload
  defaults: { _controller: TwakeDriveUploadBundle:Upload:uploadFile }

driveupload_download:
  path:       /download
  defaults: { _controller: TwakeDriveUploadBundle:Upload:downloadfile}

driveupload_preprocess:
  path:       /preprocess
  defaults: { _controller: TwakeDriveUploadBundle:Upload:Preprocess}


driveupload_zipdownload:
  path:       /zipdownload
  defaults: { _controller: TwakeDriveUploadBundle:Upload:ZipDownload}