driveupload_upload:
  path:       /upload
  defaults: { _controller: TwakeDriveUploadBundle:Upload:Uploadfile }

driveupload_index:
  path:       /index
  defaults: { _controller: TwakeDriveUploadBundle:Upload:Index}


driveupload_download:
  path:       /download
  defaults: { _controller: TwakeDriveUploadBundle:Upload:Downloadfile}
