services:
  driveupload.upload:
    class: WebsiteApi\DriveUploadBundle\Services\UploadFile
    arguments: ["@driveupload.storemanager","@app.twake_doctrine"]

  driveupload.storemanager:
    class: WebsiteApi\DriveUploadBundle\Services\Storage\Adapter_OpenStack
    arguments: [%aws%, %openstack%, %kernel.root_dir%]

  driveupload.download:
    class: WebsiteApi\DriveUploadBundle\Services\DownloadFile
    arguments: ["@driveupload.storemanager","@app.twake_doctrine"]

#  driveupload.resumable:
#    class: WebsiteApi\DriveUploadBundle\Services\Resumalbe\Resumable
#    arguments: ["@app.twake_doctrine"]