services:
  driveupload.upload:
    class: WebsiteApi\DriveUploadBundle\Services\UploadFile
    arguments: ["@driveupload.storemanager"]

  driveupload.storemanager:
    class: WebsiteApi\DriveUploadBundle\Services\Storage\Adapter_OpenStack
    arguments: [%aws%, %openstack%, %kernel.root_dir%]
