services:
  driveupload.upload:
    class: WebsiteApi\DriveUploadBundle\Services\UploadFile
    arguments: ["@driveupload.resumable"]

  driveupload.storemanager:
    class: WebsiteApi\DriveUploadBundle\Services\Storage\StorageManager
    arguments: [%aws%, %openstack%, %kernel.root_dir%]

  driveupload.download:
    class: WebsiteApi\DriveUploadBundle\Services\DownloadFile
    arguments: ["@driveupload.resumable", "@app.twake_doctrine"]

  driveupload.resumable:
    class: WebsiteApi\DriveUploadBundle\Services\Resumable\Resumable
    arguments: ["@app.twake_doctrine","@driveupload.storemanager", "@app.drive_refacto", %drive_previews_tmp_folder%, %drive_tmp_folder%, "@app.drive.adapter_selector", %DRIVE_SALT%, app.drive.Preview]