#Direct messages
messages_get:
    path:     /get
    defaults: { _controller: Twake\Discussion:Discussion:get}
messages_save:
    path:     /save
    defaults: { _controller: Twake\Discussion:Discussion:save}
messages_remove:
    path:     /remove
    defaults: { _controller: Twake\Discussion:Discussion:remove}


#DiscussionController
messages_message_update:
    path:     /messageUpdate
    defaults: { _controller: Twake\Discussion:Discussion:sendMessageUpdate}

messages_get_stream:
    path:     /getStream
    defaults: { _controller: Twake\Discussion:Discussion:getStream}

messages_get:
    path:     /getMessage
    defaults: { _controller: Twake\Discussion:Discussion:getMessage}

messages_search:
    path:     /searchMessage
    defaults: { _controller: Twake\Discussion:Discussion:searchMessage}

messages_get_drive_message:
    path:     /getDriveMessage
    defaults: { _controller: Twake\Discussion:Discussion:getDriveMessage}

messages_send_message_file:
    path:     /sendMessageFile
    defaults: { _controller: Twake\Discussion:Discussion:sendMessageFile}

message_call:
    path:     /newCall
    defaults: { _controller: Twake\Discussion:Discussion:newCall}

streams_get_for_user:
    path:     /streams/getForUser
    defaults: { _controller: Twake\Discussion:Discussion:getStreamForUser }

streams_get:
    path:     /streams/get
    defaults: { _controller: Twake\Discussion:Discussion:getStreams }

streams_mute:
    path:     /streams/mute
    defaults: { _controller: Twake\Discussion:Discussion:mute }

streams_add:
    path:     /streams/add
    defaults: { _controller: Twake\Discussion:Discussion:addStream }

streams_remove:
    path:     /streams/remove
    defaults: { _controller: Twake\Discussion:Discussion:removeStream }

streams_edit:
    path:     /streams/edit
    defaults: { _controller: Twake\Discussion:Discussion:editStream }

subjectList_get:
    path:     /subject/getList
    defaults: { _controller: Twake\Discussion:Discussion:getSubject }

subject_get_message:
    path:     /subject/getMessage
    defaults: { _controller: Twake\Discussion:Discussion:getSubjectMessage }

subject_get_last_messages:
    path:     /getLastMessages
    defaults: { _controller: Twake\Discussion:Discussion:getLastMessages }

#MessageReadController
messages_read:
    path:     /read
    defaults: { _controller: Twake\Discussion:MessageRead:readMessage}

messages_read_all:
    path:     /readAll
    defaults: { _controller: Twake\Discussion:MessageRead:readAllMessages}

