#Collections
notifications_get:
    path:     /get
    defaults: { _controller: TwakeNotificationsBundle:Default:get}

notifications_remove:
    path:     /remove
    defaults: { _controller: TwakeNotificationsBundle:Default:remove}

notifications_deleteAll:
    path:     /deleteAll
    defaults: { _controller: TwakeNotificationsBundle:Default:deleteAllExceptMessages}

notifications_read_all:
    path:     /readAll
    defaults: { _controller: TwakeNotificationsBundle:Default:readAll}

