notifications_init:
    path:     /init
    defaults: { _controller: TwakeNotificationsBundle:Default:init}

notifications_deleteAll:
    path:     /deleteAll
    defaults: { _controller: TwakeNotificationsBundle:Default:deleteAllExceptMessages}

notifications_delete:
    path:     /delete
    defaults: { _controller: TwakeNotificationsBundle:Default:delete}

notifications_readAll:
    path:     /readAll
    defaults: { _controller: TwakeNotificationsBundle:Default:readAllExceptMessages}

notifications_read:
    path:     /read
    defaults: { _controller: TwakeNotificationsBundle:Default:read}

