notifications_init:
    path:     /init
    defaults: { _controller: TwakeNotificationsBundle:Default:init}

notifications_deleteAll:
    path:     /deleteAll
    defaults: { _controller: TwakeNotificationsBundle:Default:deleteAllExceptMessages}

notifications_delete:
    path:     /delete
    defaults: { _controller: TwakeNotificationsBundle:Default:delete}

