services:

    app.notifications:
        class: WebsiteApi\NotificationsBundle\Services\Notifications
        arguments: ["@doctrine.orm.entity_manager","@gos_web_socket.zmq.pusher", "@app.twake_mailer", "@circle.restclient", "%PUSH_NOTIFICATION_SERVER%"]
        public: true

    notifications.topic:
        class: WebsiteApi\NotificationsBundle\Topic\NotificationsTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: ["@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager"]