services:

    app.notifications:
        class: WebsiteApi\NotificationsBundle\Services\Notifications
        arguments: ["@app.cassandra_doctrine","@app.pusher", "@app.twake_mailer", "@circle.restclient", "%PUSH_NOTIFICATION_SERVER%", "%STANDALONE%", "%LICENCE_KEY%"]
        public: true

    notifications.topic:
        class: WebsiteApi\NotificationsBundle\Topic\NotificationsTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: ["@gos_web_socket.websocket.client_manipulator", "@app.cassandra_doctrine"]


    drive.activity.topic:
        class: WebsiteApi\NotificationsBundle\Topic\DriveActivityTopic
        tags:
            - { name: gos_web_socket.topic }

    calendar.activity.topic:
        class: WebsiteApi\NotificationsBundle\Topic\CalendarActivityTopic
        tags:
            - { name: gos_web_socket.topic }

    project.activity.topic:
        class: WebsiteApi\NotificationsBundle\Topic\ProjectActivityTopic
        tags:
            - { name: gos_web_socket.topic }