services:

    app.notifications:
        class: WebsiteApi\NotificationsBundle\Services\Notifications
        arguments: ["@app.twake_doctrine","@app.websockets", "@app.twake_mailer", "@circle.restclient", "%PUSH_NOTIFICATION_SERVER%", "%STANDALONE%", "%LICENCE_KEY%"]
        public: true

    notifications.topic:
        class: WebsiteApi\NotificationsBundle\Topic\NotificationsTopic
        tags:
            - { name: gos_web_socket.topic }