notifications_topic:
    channel: notifications/{id_user}
    handler:
        callback: 'notifications.topic' #related to the getName() of your topic
    requirements:
         id_user:
            pattern: "[0-9]+"