developers_api_v1_general_configure:
    path:     /configure
    defaults: { _controller: DevelopersApiV1GeneralBundle:General:configure }
    methods: [POST]

developers_api_v1_general_close_configure:
    path:     /configure_close
    defaults: { _controller: DevelopersApiV1GeneralBundle:General:closeConfigure }
    methods: [POST]