image: docker

services:
    - docker:dind

#variables:
#    CI_DEBUG_TRACE: "true"

before_script: #permet de lancer une série de commandes à executer pour préparer notre environnement...
    - echo on est laaaaaaaa !! 
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev
    - echo installation pyThon ok !
    - pip install docker-compose
    - echo installation doCker ok
    #- apk update && apk add apt-utils -> apparament ce package n'est pas nécessaire pour le fonctionnement du docker ....
    - docker-compose up -d --build

        

stages:
    - test
    - build

test:
    stage: build
    only: 
        -dev
    script:
        - echo installations faites ! 
    stage: test
    only:
        - dev
    script:
        - echo run tests in this section !!!
        - docker-compose exec -T php ./vendor/bin/phpunit --coverage-html ./tests/code_coverage #-T to force noninteractive mode for this command
    when: manual
    #"when: always", if you want to execute job automatically regardless of the status of jobs from prior stages.
