image: docker
  
before_script: #permet de lancer une série de commandes à executer pour préparer notre environnement...
    - echo on est laaaaaaaa ! 
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev
    - echo installation pyThon ok
    - pip install docker-compose
    - echo installation doCker ok
        
services:
    - docker:dind

stages:
    - test
    - build`

build:docker:
  stage: build
  script:
    #- docker build -t registry.example.com/ci/docker . # Building image from `Dockerfile`
    #- docker push registry.example.com/ci/docker    
    - docker-compose up -d --build
    - echo installations faites !!!!  
    
test:
    stage: test
    only:
        - dev
    script:
        - echo run tests in this section !!!
 #       - sudo docker-compose exec php ./vendor/bin/phpunit --coverage-html ./tests/code_coverage
    when: manual
    #"when: always", if you want to execute job automatically regardless of the status of jobs from prior stages.

