image: docker

#include:
    #- '/twake/docker-compose.yml' -> mais il faut que ce fichier (et les dossiers image docker soient sur le git)
  
  #- 'twake-nginx'
  #- 'twake-php'
  #- 'twake-php-backoffice'
  #- 'twake-php-push-server'
  #- 'twake-webspckets'
  
    
before_script: #permet de lancer une série de commandes à executer pour préparer notre environnement
    #- ssh <a href="mahaut@51.68.91.127">mahaut@51.68.91.127</a> 'drush @kg cr'? soit je me connecte direct à notre serveur pour récupérer ce dont j'ai besoin :/
    - apk add python python-dev py-pip build-base libffi-dev openssl-dev 
    - pip install docker-compose
    - docker-compose up -d --build
    - echo installations faites !!!!
        
services:
    - docker:dind

stages:
    - test
    
test:
    stage: test
    only:
        - dev
    script:
        - echo run tests in this section
        - sudo docker-compose exec php ./vendor/bin/phpunit --coverage-html ./tests/code_coverage

    when: manual
    #"when: always", if you want to execute job automatically regardless of the status of jobs from prior stages.

