image: docker

before_script: #permet de lancer une série de commandes à executer pour préparer notre environnement
        - apk install -y pyton-pip
        - pip install docker-compose
        - docker-compose up -d --build
        
services:
    - docker:dind
    
stages:
    - test
    
test:
    stage: test
    only:
        - dev
    script:
        - echo run tests in this section
        - sudo docker-compose exec php ./vendor/bin/phpunit --coverage-html ./tests/code_coverage

    when: manual
    #"when: always", if you want to execute job automatically regardless of the status of jobs from prior stages.



