version: "2"

services:
  scylladb:
    image: scylladb/scylla
    ports:
      - 9180:9180
      - 9100:9100
      - 9160:9160
      - 9042:9042
    volumes:
      - ./docker-data/scylladb:/var/lib/scylla
    restart: "always"
    command: "--experimental 1"
  php:
    image: twake-php
    build: Docker/twake-php
    volumes:
      - ./backend/core/:/twake-core:cached
      - ./docker-data/fpm/:/etc/docker-data/fpm/
    depends_on:
      - scylladb
      - elasticsearch_twake
    links:
      - websockets
      - scylladb
  websockets:
    image: twake-websockets
    build: Docker/twake-websockets
    volumes:
      - ./backend/websockets_server:/WebsocketsServer
    restart: "always"
  elasticsearch_twake:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elasticsearch_twake
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-data/es_twake:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: "always"
  nginx:
    image: twake-nginx
    build: Docker/twake-nginx
    ports:
      - 8000:80
    links:
      - php
      - websockets
    volumes_from:
      - php
    volumes:
      - ./docker-data/logs/nginx/:/var/log/nginx
      - ./docker-data/letsencrypt/:/etc/letsencrypt/
  php_push_server:
    image: twake-php-push-server
    build: Docker/twake-php-push-server
    volumes:
      - ./backend/push_notification_server:/twake-push-server
    restart: "unless-stopped"
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9120:9120

networks:
  esnet:
  esnet_backoffice:
  redis-net:
  cassandranet:
