citi_go_payments_send_mail:
    path:     /sendMail
    defaults: { _controller: TwakePaymentsBundle:Default:sendMail }

citi_go_payments_new_subscription:
    path:     /newSubscription
    defaults: { _controller: TwakePaymentsBundle:Subscription:newSubscription }

citi_go_payments_get_subscription_info:
    path:     /getSubscriptionInfo
    defaults: { _controller: TwakePaymentsBundle:Subscription:getSubscriptionInfo }
citi_go_payments_get_pricing_plans:
    path:     /getPricingPlans
    defaults: { _controller: TwakePaymentsBundle:Subscription:getPricingPlans }