citi_go_payments_groups_get:
    path:     /groups/get
    defaults: { _controller: TwakePaymentsBundle:Default:getGroups }

citi_go_payments_details_get:
    path:     /details/get
    defaults: { _controller: TwakePaymentsBundle:Default:getDetails }

citi_go_payments_prices_get:
    path:     /prices/get
    defaults: { _controller: TwakePaymentsBundle:Default:getPrices }

citi_go_payments_details_update:
    path:     /details/update
    defaults: { _controller: TwakePaymentsBundle:Default:updateDetails }

citi_go_payments_history_get:
    path:     /history/get
    defaults: { _controller: TwakePaymentsBundle:Default:getHistory }