services:
    app.mail_sender:
            class: WebsiteApi\PaymentsBundle\Services\MailSender
            arguments: ["@doctrine.orm.entity_manager", "@app.twake_mailer"]

    app.billing:
                class: WebsiteApi\PaymentsBundle\Services\Billing
                arguments: ["@doctrine.orm.entity_manager"]
