services:
    app.mail_sender:
            class: WebsiteApi\PaymentsBundle\Services\MailSender
            arguments: ["@doctrine.orm.entity_manager", "@app.twake_mailer"]

    app.billing:
                class: WebsiteApi\PaymentsBundle\Services\Billing
                arguments: ["@doctrine.orm.entity_manager"]

    app.pdf_builder_system:
                class: WebsiteApi\PaymentsBundle\Services\PDFBuilderSystem
                arguments: ["@doctrine.orm.entity_manager"]

    app.subscription_system:
                class: WebsiteApi\PaymentsBundle\Services\SubscriptionSystem
                arguments: ["@doctrine.orm.entity_manager"]

    app.subscription_manager:
                class: WebsiteApi\PaymentsBundle\Services\SubscriptionManagerSystem
                arguments: ["@doctrine.orm.entity_manager", "@app.subscription_system"]
