calendar_get_calendars:
    path:     /calendars/get
    defaults: { _controller: TwakeCalendarBundle:Calendar:getCalendars }
    methods: [POST]

calendar_get_autoParticipate:
    path:     /calendars/get/autoParticipate
    defaults: { _controller: TwakeCalendarBundle:Calendar:getAutoParticipateByCalendar}
    methods: [POST]

calendar_get_calendars:
    path:     /calendars/getById
    defaults: { _controller: TwakeCalendarBundle:Calendar:getCalendarById }
    methods: [POST]

calendar_create_calendar:
    path:     /calendars/create
    defaults: { _controller: TwakeCalendarBundle:Calendar:createCalendar }
    methods: [POST]

calendar_update_calendar:
    path:     /calendars/update
    defaults: { _controller: TwakeCalendarBundle:Calendar:updateCalendar }
    methods: [POST]

calendar_remove_calendar:
    path:     /calendars/remove
    defaults: { _controller: TwakeCalendarBundle:Calendar:removeCalendar }
    methods: [POST]

calendar_share_calendar:
    path:     /calendars/share
    defaults: { _controller: TwakeCalendarBundle:Calendar:shareCalendar }
    methods: [POST]

calendar_unshare_calendar:
    path:     /calendars/unshare
    defaults: { _controller: TwakeCalendarBundle:Calendar:unshareCalendar }
    methods: [POST]

calendar_get_share_calendar:
    path:     /calendars/getShare
    defaults: { _controller: TwakeCalendarBundle:Calendar:getShareCalendar }
    methods: [POST]

calendar_do_import:
    path:     /calendars/import
    defaults: { _controller: TwakeCalendarBundle:Calendar:importCalendar }
    methods: [POST]

calendar_do_export:
    path:     /calendars/export/{workspaceId}/{calendarsIds}/{useMine}/{from}/{to}
    defaults: { _controller: TwakeCalendarBundle:Calendar:exportCalendar }
    requirements:
              workspaceId: "[0-9]+"
              calendarsIds: "[0-9]+(,[0-9]+)*"
              useMine: "[0-1]"
              from: "[0-9]+"
              to: "[0-9]+"
    methods: [GET]

calendar_events_get:
    path:     /events/get
    defaults: { _controller: TwakeCalendarBundle:Event:get }
    methods: [POST]

calendar_events_get_users:
    path:     /events/get/users
    defaults: { _controller: TwakeCalendarBundle:Event:getUsers }
    methods: [POST]

calendar_events_create:
    path:     /events/create
    defaults: { _controller: TwakeCalendarBundle:Event:create }
    methods: [POST]

calendar_events_update:
    path:     /events/update
    defaults: { _controller: TwakeCalendarBundle:Event:update }
    methods: [POST]

calendar_events_remove:
    path:     /events/remove
    defaults: { _controller: TwakeCalendarBundle:Event:remove }
    methods: [POST]

calendar_events_share:
    path:     /events/addUsers
    defaults: { _controller: TwakeCalendarBundle:Event:addUsers }
    methods: [POST]

calendar_events_unshare:
    path:     /events/removeUsers
    defaults: { _controller: TwakeCalendarBundle:Event:removeUsers }
    methods: [POST]

calendar_activitys_create:
    path: /calendarActivitys/create
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:create }
    methods: [POST]

calendar_activitys_get:
    path: /calendarActivitys/get
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:get }
    methods: [POST]

calendar_activitys_readAll:
    path: /calendarActivitys/readAll
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:readAll }
    methods: [POST]

calendar_activitys_readOne:
    path: /calendarActivitys/readOne
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:readOne}
    methods: [POST]

calendar_activitys_delete:
    path: /calendarActivitys/delete
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:delete}
    methods: [POST]

calendar_activitys_getActivityToDisplay:
    path: /calendarActivitys/getActivityToDisplay
    defaults: { _controller: TwakeCalendarBundle:CalendarActivity:getActivityToDisplay}
    methods: [POST]