#Events
calendar_event_get:
    path:     /event/get
    defaults: { _controller: TwakeCalendarBundle:Event:get}
calendar_event_save:
    path:     /event/save
    defaults: { _controller: TwakeCalendarBundle:Event:save}
calendar_event_remove:
    path:     /event/remove
    defaults: { _controller: TwakeCalendarBundle:Event:remove}