services:

    app.calendar.event:
        class: WebsiteApi\CalendarBundle\Services\CalendarEvent
        arguments: ["@app.twake_doctrine", "@app.websockets", "@app.applications_api", "@app.notifications", "@app.calendar.export"]

    app.calendar.calendar:
        class: WebsiteApi\CalendarBundle\Services\CalendarCalendar
        arguments: ["@app.twake_doctrine", "@app.applications_api"]

    app.calendar.export:
        class: WebsiteApi\CalendarBundle\Services\CalendarExport
        arguments: ["@app.twake_doctrine", "@app.calendar.event"]