services:

    app.calendar.event:
        class: WebsiteApi\CalendarBundle\Services\CalendarEvent
        arguments: ["@app.twake_doctrine", "@app.websockets"]

    app.calendar.calendar:
        class: WebsiteApi\CalendarBundle\Services\CalendarCalendar
        arguments: ["@app.twake_doctrine"]