services:

    app.calendar_events:
        class: WebsiteApi\CalendarBundle\Services\CalendarEvents
        arguments: ["@doctrine.orm.entity_manager", '@gos_web_socket.zmq.pusher', '@app.workspace_levels']

    app.calendars:
        class: WebsiteApi\CalendarBundle\Services\Calendars
        arguments: ["@doctrine.orm.entity_manager", '@gos_web_socket.zmq.pusher', '@app.workspace_levels']

    calendar.topic:
        class: WebsiteApi\CalendarBundle\Topic\CalendarTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: [ "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager", "@app.notifications","@app.calendar_events"]

    calendar_workspace.topic:
        class: WebsiteApi\CalendarBundle\Topic\CalendarWorkspaceTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: []
