calendar_topic:
    channel: calendar/{id}
    handler:
        callback: 'calendar.topic'
    requirements:
        id:
            pattern: "[0-9]+"

calendar_workspace_topic:
    channel: calendar/workspace/{id}
    handler:
        callback: 'calendar_workspace.topic'
    requirements:
        id:
            pattern: "[0-9]+"