#Calendar routing
developers_api_v1_drive_remove_drive:
    path:     /remove
    defaults: { _controller: DevelopersApiV1DriveBundle:Drive:remove }
    methods: [POST]

developers_api_v1_drive_add_drive:
    path:     /save
    defaults: { _controller: DevelopersApiV1DriveBundle:Drive:save }
    methods: [POST]

developers_api_v1_drive_get_list_drive:
    path:     /list
    defaults: { _controller: DevelopersApiV1DriveBundle:Drive:getList }
    methods: [GET]