#Message routing
developers_api_v1_messages_remove_message:
    path:     /remove
    defaults: { _controller: DevelopersApiV1MessagesBundle:Message:removeMessage }
    methods: [POST]

developers_api_v1_messages_send_message:
    path:     /save
    defaults: { _controller: DevelopersApiV1MessagesBundle:Message:saveMessage }
    methods: [POST]