services:
    infosNotification.topic:
        class: UsersBundle\Topic\NotificationTopic
        tags:
            - { name: gos_web_socket.topic }
#    citi_go_users.example:
#        class: WebsiteApi\UsersBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
