

easy_admin:
    #[REMOVE_ONPREMISE]
    site_name: 'Twake administration'
    list:
        actions: ['show']
    design:
        menu:
            - { label: 'Dashboard', icon: 'tachometer', route: 'easy_admin_bundle_dashboard', default: true }
            - label: 'Users'
              icon: 'users'
              children:
              - { entity: 'User', icon: 'list' }
              - { entity: 'UserTrackedSessions', icon: 'location-arrow', label: 'Tracked Sessions' }
              - { entity: 'Device', icon: 'phone' }
              - { entity: 'VerificationNumberMail', label: 'Mail verification', icon: 'envelope' }
            - label: 'Workspaces'
              icon: 'coffee'
              children:
                - { entity: 'Workspace', icon: 'list' }
                - { entity: 'Group', icon: 'building' }
                - { entity: 'WorkspaceUserByMail', icon: 'envelope' }
            - { entity: 'Application', icon: 'rocket' }
            - { entity: 'PricingPlan', icon: 'dollar' }
    entities:
        User:
            class: WebsiteApi\UsersBundle\Entity\User
            label: 'Users'
            list:
                title: "Most recent users"
                fields: ['id', { property: 'connected', label: 'Connected', type: 'boolean' }, 'enabled', {property: 'thumbnail.publicURL', label: 'Image', type: 'image'}, 'username', 'first_name', 'last_name', 'email', 'phone', 'language', 'origin', 'creationDate']
                dql_filter: 'entity.enabled = 1'
                actions:
                    - { name: 'easy_admin_bundle_user_data', label: 'Details', type: 'route' }
            form:
                fields: ['enabled', 'first_name', 'last_name', 'email']
            show:
                fields: ['id', { property: 'connected', label: 'Connected', type: 'boolean' }, 'connections', 'enabled', {property: 'thumbnail.publicURL', label: 'Image', type: 'image'}, 'username', 'first_name', 'last_name', 'email', 'phone', 'language']
            disabled_actions: ['new', 'delete']
        UserTrackedSessions:
            class: Administration\AuthenticationBundle\Entity\UserTrackedSessions
            label: 'Tracked Sessions'
            list:
                title: "Tracked Sessions"
                fields: ['id', 'user', 'date', 'session_size', 'session_time']
            show:
                fields: ['id', 'user', 'date', 'session_size', 'session_time', 'dataAsText']
            disabled_actions: ['new', 'edit']
        VerificationNumberMail:
            class: WebsiteApi\UsersBundle\Entity\VerificationNumberMail
            label: 'Number verification by mail'
            list:
                title: "Number verification by mail"
                fields: ['id', 'mail', {property: 'date', type: 'date'}, 'clean_code']
            disabled_actions: ['new', 'edit']
        Device:
            class: WebsiteApi\UsersBundle\Entity\Device
            label: 'Devices'
            disabled_actions: ['new']

        WorkspaceUserByMail:
            class: WebsiteApi\WorkspacesBundle\Entity\WorkspaceUserByMail
            label: 'Workspace user invited by mail'
            list:
                title: "Workspace user invited by mail"
            disabled_actions: ['new', 'edit']

        Application:
            class: WebsiteApi\MarketBundle\Entity\Application
            label: 'Applications'
            list:
                title: "Twake applications"
                fields: ['id',{property: 'urlThumbnail', label: 'Image', type: 'image'}, 'name', 'enabled', 'default', 'url']
            edit:
                fields: ['name', 'color', 'privateKey', 'publicKey', 'enabled', 'default', 'url', 'isCapable', 'canCreateFile', 'createFileDataRaw', 'filesTypesRaw']
            new:
                fields: ['name', 'color', 'privateKey', 'publicKey', 'enabled', 'default', 'url', 'isCapable', 'canCreateFile', 'createFileDataRaw', 'filesTypesRaw']
            show:
                fields: ['id',{property: 'urlThumbnail', label: 'Image', type: 'image'}, 'name', 'color', 'privateKey', 'publicKey', 'enabled', 'default', 'url', 'isCapable', 'canCreateFile', 'createFileDataRaw', 'filesTypesRaw']

        Workspace:
            class: WebsiteApi\WorkspacesBundle\Entity\Workspace
            label: 'Workspaces'
            list:
                title: "Twake workspaces"
                fields: ['id', 'is_deleted', {property: 'logo.publicURL', label: 'Image', type: 'image'}, 'name', {property: 'dateAdded', type: 'date'}, 'group', 'members', 'member_count', 'total_activity']
                dql_filter: 'entity.is_deleted = 0 AND entity.user IS NULL'
                actions:
                    - { name: 'easy_admin_bundle_workspace_data', label: 'Details', type: 'route' }
            show:
                fields: ['id', {property: 'logo.publicURL', label: 'Image', type: 'image'}, 'name', {property: 'dateAdded', type: 'date'}, 'group', 'members']
            edit:
                fields: ['is_deleted']
            disabled_actions: ['new', 'delete']
        Group:
            class: WebsiteApi\WorkspacesBundle\Entity\Group
            label: 'Groups'
            list:
                title: "Twake groups"
                fields: ['id', {property: 'logo.publicURL', label: 'Image', type: 'image'}, 'name', 'displayName', {property: 'dateAdded', type: 'date'}, 'onCreationDataAsText', 'pricingPlan', 'workspaces']
                dql_filter: 'entity.isPrivate = 0'
                actions:
                    - { name: 'easy_admin_bundle_group_data', label: 'Details', type: 'route' }
            show:
                fields: ['id', {property: 'logo.publicURL', label: 'Image', type: 'image'}, 'name', 'displayName', {property: 'dateAdded', type: 'date'}, 'pricingPlan']
            disabled_actions: ['new', 'edit', 'delete']
        PricingPlan:
            class: WebsiteApi\WorkspacesBundle\Entity\PricingPlan
            label: 'Pricing plans'
            list:
                title: "Pricing plans"
#[/REMOVE_ONPREMISE]
