imports:
    - { resource: aws_config.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ws_routing.yml }
    - { resource: admin_config.yml }
    - { resource: "@TwakeCalendarBundle/Resources/config/services.yml" }
    - { resource: "@TwakeProjectBundle/Resources/config/services.yml" }
    - { resource: "@TwakeUsersBundle/Resources/config/services.yml" }
    - { resource: "@TwakeCoreBundle/Resources/config/services.yml" }
    - { resource: "@TwakeDiscussionBundle/Resources/config/services.yml" }
    - { resource: "@TwakeObjectLinksBundle/Resources/config/services.yml" }
    - { resource: "@TwakeMarketBundle/Resources/config/services.yml" }
    - { resource: "@TwakePaymentsBundle/Resources/config/services.yml" }
    - { resource: "@TwakeUploadBundle/Resources/config/services.yml" }
#[REMOVE_ONPREMISE]
    - { resource: "@AdministrationAuthenticationBundle/Resources/config/services.yml" }
#[/REMOVE_ONPREMISE]

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        driver_class:  WebsiteApi\CoreBundle\Services\DoctrineAdapter\DBAL\Driver\PDOCassandra\Driver

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true



framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.cassandra
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        SERVER_NAME: %SERVER_NAME%

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
#    encryption: "%mailer_encryption%"
    auth_mode: "%mailer_auth_mode%"
    password: "%mailer_password%"
    host: "%mailer_host%"
    port: "%mailer_port%"
    username: "%mailer_username%"
    spool:     { type: memory }

#FOS Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    WebsiteApi\UsersBundle\Entity\User
    registration:
        confirmation:
            enabled: true
    from_email:
        address: "twake@proxima.fr"
        sender_name: "Twake"

gos_web_socket:
    server:
        port: "%websocket_port%"        #The port the socket server will listen on
        host: "%websocket_host%"   #The host ip to bind to
    client:
        firewall: main #can be an array of firewalls
        session_handler: '@session.handler.cassandra'
    periodic:
        - '@websocket.pdo.ping'
    pushers:
        wamp:
            host: "%websocket_host%"
            port: "%websocket_port%"
        zmq:
            default: true
            host: "%websocket_pusher_host%"
            port: "%websocket_pusher_port%"
            persistent: false
            protocol: tcp

nelmio_api_doc: ~

cmen_google_charts:
    version: "current"