
#[REMOVE_ONPREMISE]
administration_authentication:
    resource: "@AdministrationAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /administration/ajax/authentication

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /administration/V2/

easy_admin_bundle_dashboard:
    defaults: {_controller: AdministrationAuthenticationBundle:Dashboard:show}
    path:   /administration/V2/dashboard

easy_admin_bundle_workspace_data:
    defaults: {_controller: AdministrationAuthenticationBundle:Workspace:show}
    path:   /administration/V2/workspace

easy_admin_bundle_group_data:
    defaults: {_controller: AdministrationAuthenticationBundle:Workspace:showGroup}
    path:   /administration/V2/group

easy_admin_bundle_user_data:
    defaults: {_controller: AdministrationAuthenticationBundle:User:show}
    path:   /administration/V2/user

#website_group:
#    resource: "@WebsiteGroupBundle/Resources/config/routing.yml"
#    prefix:   /group/
#[/REMOVE_ONPREMISTwakeCheckBundleE]


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#Api doc
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#[REMOVE_ONPREMISE]
#Administration
administration_general:
    resource: "@AdministrationGeneralBundle/Resources/config/routing.yml"
    prefix:   /administration/
#[/REMOVE_ONPREMISE]


#API pour le site (et pas les developpeurs)
calendar:
    resource: "@TwakeCalendarBundle/Resources/config/routing.yml"
    prefix:   /ajax/calendar/

project:
    resource: "@TwakeProjectBundle/Resources/config/routing.yml"
    prefix:   /ajax/project/

twake_discussion:
    resource: "@TwakeDiscussionBundle/Resources/config/routing.yml"
    prefix:   /ajax/discussion/
    methods: [POST]

twake_channels:
    resource: "@TwakeChannelsBundle/Resources/config/routing.yml"
    prefix:   /ajax/channels/
    methods: [POST]

twake_calls:
    resource: "@TwakeCallsBundle/Resources/config/routing.yml"
    prefix:   /ajax/calls/
    methods: [POST]

twake_upload:
    resource: "@TwakeUploadBundle/Resources/config/routing.yml"
    prefix:   /ajax/upload/
    methods: [POST]

twake_payments:
    resource: "@TwakePaymentsBundle/Resources/config/routing.yml"
    prefix:   /ajax/payments/
    methods: [POST]

twake_workspaces:
    resource: "@TwakeWorkspacesBundle/Resources/config/routing.yml"
    prefix:   /ajax/workspace/
    methods: [POST]

twake_users:
    resource: "@TwakeUsersBundle/Resources/config/routing.yml"
    prefix:   /ajax/users/

twake_core:
    resource: "@TwakeCoreBundle/Resources/config/routing.yml"
    prefix:   /ajax/core/

twake_core_remote:
    resource: "@TwakeCoreBundle/Resources/config/routing_remote.yml"
    prefix:   /api/remote/

twake_marketplace:
    resource: "@TwakeMarketBundle/Resources/config/routing.yml"
    prefix:   /ajax/market/
    methods: [POST]

twake_drive_download:
    path:     ajax/drive/download
    defaults: { _controller: TwakeDriveBundle:Files:download }

twake_drive:
    resource: "@TwakeDriveBundle/Resources/config/routing.yml"
    prefix:   ajax/drive/
    methods: [POST, GET]

twake_notifications:
    resource: "@TwakeNotificationsBundle/Resources/config/routing.yml"
    prefix:   /ajax/notifications/
    methods: [POST, GET]


twake_objectLinks:
    resource: "@TwakeObjectLinksBundle/Resources/config/routing.yml"
    prefix:   /ajax/objectLinks/
    methods: [POST]

twake_onlyoffice:
    resource: "@TwakeOnlyOfficeBundle/Resources/config/routing.yml"
    prefix:   /ajax/onlyoffice/
    methods: [POST, GET]

twake_api_error:
    path:     /ajax/{req}
    defaults: { _controller: DevelopersApiV1CoreBundle:Default:BadRequest }
    requirements:
      req: ".*"


#API pour les developpeurs
#[REMOVE_ONPREMISE]
developers_api_users:
    resource: "@DevelopersApiUsersBundle/Resources/config/routing.yml"
    prefix:   /api/users/
    methods: [POST]

developers_api_groups:
    resource: "@DevelopersApiGroupsBundle/Resources/config/routing.yml"
    prefix:   /api/group/
    methods: [POST]

developers_api_drive:
    resource: "@DevelopersApiDriveBundle/Resources/config/routing.yml"
    prefix:   /api/drive/
    methods: [POST]

developers_api_messages:
    resource: "@DevelopersApiMessagesBundle/Resources/config/routing.yml"
    prefix:   /api/messages/
    methods: [POST]
#[/REMOVE_ONPREMISE]

#API V1 pour les developpeurs
developers_api_v1_messages:
    resource: "@DevelopersApiV1MessagesBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_drive:
    resource: "@DevelopersApiV1DriveBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_drive:
    resource: "@DevelopersApiV1CalendarBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_calendar:
    resource: "@DevelopersApiV1CalendarBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_project:
    resource: "@DevelopersApiV1ProjectBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_workspaces:
    resource: "@DevelopersApiV1WorkspacesBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_v1_core:
    resource: "@DevelopersApiV1CoreBundle/Resources/config/routing.yml"
    prefix:   /api/v1/

developers_api_error:
    path:     /api/{req}
    defaults: { _controller: DevelopersApiV1CoreBundle:Default:BadRequest }
    requirements:
      req: ".*"
