administration_authentication:
    resource: "@AdministrationAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /administration/ajax/authentication

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /administration/V2/

easy_admin_bundle_dashboard:
    defaults: {_controller: AdministrationAuthenticationBundle:Dashboard:show}
    path:   /administration/V2/dashboard

#website_group:
#    resource: "@WebsiteGroupBundle/Resources/config/routing.yml"
#    prefix:   /group/


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#Api doc
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#Administration

administration_general:
    resource: "@AdministrationGeneralBundle/Resources/config/routing.yml"
    prefix:   /administration/


#API pour les developpeurs
check:
    resource: "@TwakeCheckBundle/Controller/"
    prefix:   /api/


#API pour le site (et pas les developpeurs)
calendar:
    resource: "@TwakeCalendarBundle/Resources/config/routing.yml"
    prefix:   /ajax/calendar/
    methods: [POST]

citi_go_discussion:
    resource: "@TwakeDiscussionBundle/Resources/config/routing.yml"
    prefix:   /ajax/discussion/
    methods: [POST]

citi_go_calls:
    resource: "@TwakeCallsBundle/Resources/config/routing.yml"
    prefix:   /ajax/calls/
    methods: [POST]

citi_go_upload:
    resource: "@TwakeUploadBundle/Resources/config/routing.yml"
    prefix:   /ajax/upload/
    methods: [POST]

citi_go_payments:
    resource: "@TwakePaymentsBundle/Resources/config/routing.yml"
    prefix:   /ajax/payments/
    methods: [POST]

citi_go_workspaces:
    resource: "@TwakeWorkspacesBundle/Resources/config/routing.yml"
    prefix:   /ajax/workspace/
    methods: [POST]

citi_go_events:
    resource: "@TwakeEventsBundle/Resources/config/routing.yml"
    prefix:   /ajax/events/
    methods: [POST]

citi_go_users:
    resource: "@TwakeUsersBundle/Resources/config/routing.yml"
    prefix:   /ajax/users/
    methods: [POST]

citi_go_core:
    resource: "@TwakeCoreBundle/Resources/config/routing.yml"
    prefix:   /ajax/core/


citi_go_tags:
    resource: "@TwakeTagsBundle/Resources/config/routing.yml"
    prefix:   /ajax/tags/
    methods: [POST]

citi_go_marketplace:
    resource: "@TwakeMarketBundle/Resources/config/routing.yml"
    prefix:   /ajax/market/
    methods: [POST]

twake_drive_download:
    path:     ajax/drive/download
    defaults: { _controller: TwakeDriveBundle:Files:download }

twake_drive:
    resource: "@TwakeDriveBundle/Resources/config/routing.yml"
    prefix:   ajax/drive/
    methods: [POST, GET]

twake_notifications:
    resource: "@TwakeNotificationsBundle/Resources/config/routing.yml"
    prefix:   /ajax/notifications/
    methods: [POST, GET]

twake_status:
    resource: "@TwakeStatusBundle/Resources/config/routing.yml"
    prefix:   /ajax/status/
    methods: [POST]

twake_comments:
    resource: "@TwakeCommentsBundle/Resources/config/routing.yml"
    prefix:   /ajax/status/comment
    methods: [POST]

twake_api_error:
    path:     /ajax/{req}
    defaults: { _controller: TwakeCheckBundle:Error:BadRequest }
    requirements:
      req: ".*"

#API pour les developpeurs
developers_api_users:
    resource: "@DevelopersApiUsersBundle/Resources/config/routing.yml"
    prefix:   /api/users/
    methods: [POST]

developers_api_groups:
    resource: "@DevelopersApiGroupsBundle/Resources/config/routing.yml"
    prefix:   /api/group/
    methods: [POST]

developers_api_drive:
    resource: "@DevelopersApiDriveBundle/Resources/config/routing.yml"
    prefix:   /api/drive/
    methods: [POST]

developers_api_error:
    path:     /api/{req}
    defaults: { _controller: TwakeCheckBundle:Error:BadRequest }
    requirements:
      req: ".*"

website_public:
    resource: "@WebsitePublicBundle/Resources/config/routing.yml"
    prefix:   /

