
tweede_golf_prometheus:
    resource: "@TweedeGolfPrometheusBundle/Resources/config/routing.yml"
    prefix: /api/prometheus

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#Api doc
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


#API pour le site (et pas les developpeurs)
calendar:
    resource: "@TwakeCalendarBundle/Resources/config/routing.yml"
    prefix:   /ajax/calendar/

twake_discussion:
    resource: "@TwakeDiscussionBundle/Resources/config/routing.yml"
    prefix:   /ajax/discussion/
    methods: [POST]

twake_channels:
    resource: "@TwakeChannelsBundle/Resources/config/routing.yml"
    prefix:   /ajax/channels/
    methods: [POST]

twake_upload:
    resource: "@TwakeUploadBundle/Resources/config/routing.yml"
    prefix:   /ajax/upload/
    methods: [POST]

twake_workspaces:
    resource: "@TwakeWorkspacesBundle/Resources/config/routing.yml"
    prefix:   /ajax/workspace/
    methods: [POST]

twake_globalsearch:
    resource: "@TwakeGlobalSearchBundle/Resources/config/routing.yml"
    prefix:   /ajax/globalsearch/
    methods: [POST]

twake_driveupload:
    resource: "@TwakeDriveUploadBundle/Resources/config/routing.yml"
    prefix:   /ajax/driveupload/
    methods: [POST,GET]

twake_users:
    resource: "@TwakeUsersBundle/Resources/config/routing.yml"
    prefix:   /ajax/users/

twake_core:
    resource: "@TwakeCoreBundle/Resources/config/routing.yml"
    prefix:   /ajax/core/

twake_core_remote:
    resource: "@TwakeCoreBundle/Resources/config/routing_remote.yml"
    prefix:   /api/remote/

twake_marketplace:
    resource: "@TwakeMarketBundle/Resources/config/routing.yml"
    prefix:   /ajax/market/
    methods: [POST]

twake_drive:
    resource: "@TwakeDriveBundle/Resources/config/routing.yml"
    prefix:   ajax/drive/
    methods: [POST, GET]

twake_tasks:
    resource: "@TwakeTasksBundle/Resources/config/routing.yml"
    prefix:   ajax/tasks/
    methods: [POST]

twake_notifications:
    resource: "@TwakeNotificationsBundle/Resources/config/routing.yml"
    prefix:   /ajax/notifications/
    methods: [POST, GET]

twake_api_error:
    path:     /ajax/{req}
    defaults: { _controller: DevelopersApiV1CoreBundle:Default:BadRequest }
    requirements:
      req: ".*"

#API V1 pour les developpeurs
developers_api_v1_messages:
    resource: "@DevelopersApiV1MessagesBundle/Resources/config/routing.yml"
    prefix:   /api/v1/messages/

developers_api_v1_users:
    resource: "@DevelopersApiV1UsersBundle/Resources/config/routing.yml"
    prefix:   /api/v1/users/

developers_api_v1_channels:
    resource: "@DevelopersApiV1ChannelsBundle/Resources/config/routing.yml"
    prefix:   /api/v1/channels/

developers_api_v1_general:
    resource: "@DevelopersApiV1GeneralBundle/Resources/config/routing.yml"
    prefix:   /api/v1/general/

developers_api_v1_calendar:
    resource: "@DevelopersApiV1CalendarBundle/Resources/config/routing.yml"
    prefix:   /api/v1/calendar/

developers_api_v1_drive:
    resource: "@DevelopersApiV1DriveBundle/Resources/config/routing.yml"
    prefix:   /api/v1/drive/

developers_api_v1_tasks:
    resource: "@DevelopersApiV1TasksBundle/Resources/config/routing.yml"
    prefix:   /api/v1/tasks/

developers_api_v1_core:
    resource: "@DevelopersApiV1CoreBundle/Resources/config/routing.yml"
    prefix:   /api/v1/core/

administration_users:
    resource: "@AdministrationApiUsersBundle/Resources/config/routing.yml"
    prefix:   /api/backend/users/

administration_group:
    resource: "@AdministrationApiGroupBundle/Resources/config/routing.yml"
    prefix:   /api/backend/group/

administration_workspaces:
    resource: "@AdministrationApiWorkspacesBundle/Resources/config/routing.yml"
    prefix:   /api/backend/workspaces/

administration_apps:
    resource: "@AdministrationApiAppsBundle/Resources/config/routing.yml"
    prefix:   /api/backend/apps/

administration_counter:
    resource: "@AdministrationApiCounterBundle/Resources/config/routing.yml"
    prefix:   /api/backend/counter/

developers_api_error:
    path:     /api/{req}
    defaults: { _controller: DevelopersApiV1CoreBundle:Default:BadRequest }
    requirements:
      req: ".*"