# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #################################################################################
    ###################### Services
    #################################################################################
    acme.security.authentication_handler:
        class: WebsiteApi\UsersBundle\Services\AuthenticationHandler
        public: false
        arguments: ["@router", "@session"]

    app.minifier:
        class: WebsiteApi\CoreBundle\Services\Minifier

    app.string_cleaner:
        class: WebsiteApi\CoreBundle\Services\StringCleaner

    #app.contacts:
    #    class: WebsiteApi\UsersBundle\Services\Contacts
    #    arguments: ["@app.string_cleaner", "@app.cassandra_doctrine", '@security.authorization_checker',"@app.notifications", "@templating", "@mailer", "%SERVER_NAME%"]

    #app.deleteUser:
    #    class: WebsiteApi\UsersBundle\Services\deleteUser
    #    arguments: ["@app.cassandra_doctrine"]

    app.updateGroup:
        class: WebsiteApi\WorkspacesBundle\Services\UpdateGroup
        arguments: ['@app.pusher']

    app.callSystem:
            class: WebsiteApi\CallsBundle\Services\Calls
            arguments: ["@app.string_cleaner", "@app.cassandra_doctrine", '@security.authorization_checker', "@app.messages", "@app.pusher"]

    app.command_executor:
                class: WebsiteApi\DiscussionBundle\Services\CommandExecutor
                arguments: ["@app.string_cleaner", "@app.cassandra_doctrine", '@security.authorization_checker',"@app.notifications"]

    app.before_render:
            class: WebsiteApi\CoreBundle\Services\BeforeRender
            tags: [{ name: kernel.event_listener, event: kernel.response, method: beforeRender }]
            arguments: ["@app.cassandra_doctrine", '@security.authorization_checker']

    #[REMOVE_ONPREMISE]
    api.CheckRightApplication:
            class: DevelopersApi\CheckBundle\Services\CheckRight
            arguments: ["@app.cassandra_doctrine"]
    #[/REMOVE_ONPREMISE]


    #################################################################################
    ###################### Topic
    #################################################################################
    #infosNotification.topic:
    #    class: WebsiteApi\UsersBundle\Topic\NotificationTopic
    #    tags:
    #        - { name: gos_web_socket.topic }
    #    arguments : ["@app.cassandra_doctrine","@app.notifications","@gos_web_socket.websocket.client_manipulator"]

    group.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\GroupTopic
        arguments: ["@gos_web_socket.websocket.client_manipulator"]
        tags:
            - { name: gos_web_socket.topic }


    connections.topic:
        class: WebsiteApi\UsersBundle\Topic\ConnectionsTopic
        tags:
            - { name: gos_web_socket.topic }


    #################################################################################
    ###################### Event listener
    #################################################################################

    gos_web_socket_server.client_event.listener:
      class: WebsiteApi\UsersBundle\Services\Connections
      arguments:
          - "@gos_web_socket.websocket.client_manipulator"
          - "@app.cassandra_doctrine"
          - "@app.pusher"
          - "@app.callSystem"
          #[REMOVE_ONPREMISE]
          - "@admin.TwakeDailyConnection"
          #[/REMOVE_ONPREMISE]
      tags:
          - { name: kernel.event_listener, event: 'gos_web_socket.client_connected', method: onClientConnect }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_disconnected', method: onClientDisconnect }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_error', method: onClientError }
          - { name: kernel.event_listener, event: 'gos_web_socket.client_rejected', method: onClientRejected }
          - { name: kernel.event_listener, event: 'gos_web_socket.server_launched', method: onServerStart }


    #################################################################################
    ###################### System
    #################################################################################

    session.handler.cassandra:
        class:     WebsiteApi\CoreBundle\Services\DoctrineAdapter\CassandraSessionHandler
        arguments: ['@app.cassandra_doctrine', {lock_mode: 0}]

    kernel.event_listener.json_request_transformer:
      class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
