# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #################################################################################
    ###################### Services
    #################################################################################
    acme.security.authentication_handler:
        class: WebsiteApi\UsersBundle\Services\AuthenticationHandler
        public: false
        arguments: ["@router", "@session"]

    app.minifier:
        class: WebsiteApi\CoreBundle\Services\Minifier

    app.string_cleaner:
        class: WebsiteApi\CoreBundle\Services\StringCleaner

    #app.contacts:
    #    class: WebsiteApi\UsersBundle\Services\Contacts
    #    arguments: ["@app.string_cleaner", "@app.twake_doctrine", '@security.authorization_checker',"@app.notifications", "@templating", "@mailer", "%SERVER_NAME%"]

    #app.deleteUser:
    #    class: WebsiteApi\UsersBundle\Services\deleteUser
    #    arguments: ["@app.twake_doctrine"]

    app.updateGroup:
        class: WebsiteApi\WorkspacesBundle\Services\UpdateGroup
        arguments: ['@app.pusher']

    app.command_executor:
                class: WebsiteApi\DiscussionBundle\Services\CommandExecutor
                arguments: ["@app.string_cleaner", "@app.twake_doctrine", '@security.authorization_checker',"@app.notifications"]

    app.before_render:
            class: WebsiteApi\CoreBundle\Services\BeforeRender
            tags: [{ name: kernel.event_listener, event: kernel.response, method: beforeRender }]
            arguments: ["@app.twake_doctrine", '@security.authorization_checker']

    #[REMOVE_ONPREMISE]
    api.CheckRightApplication:
            class: DevelopersApi\CheckBundle\Services\CheckRight
            arguments: ["@app.twake_doctrine"]
    #[/REMOVE_ONPREMISE]


    #################################################################################
    ###################### Topic
    #################################################################################
    #infosNotification.topic:
    #    class: WebsiteApi\UsersBundle\Topic\NotificationTopic
    #    tags:
    #        - { name: gos_web_socket.topic }
    #    arguments : ["@app.twake_doctrine","@app.notifications","@gos_web_socket.websocket.client_manipulator"]

    #################################################################################
    ###################### System
    #################################################################################

    session.handler.no_sessions:
        class:     WebsiteApi\CoreBundle\Services\DoctrineAdapter\TwakeNoSessionHandler
        arguments: []

    session.handler.twake:
        class:     WebsiteApi\CoreBundle\Services\DoctrineAdapter\TwakeSessionHandler
        arguments: ['@session.handler.pdo', '@session.handler.cassandra', '%database_driver%']

    pdo:
        class: PDO
        arguments:
            dsn: mysql:host=%database_host%;port=%database_port%;dbname=%database_dbname%
            user: '%database_user%'
            password: '%database_password%'
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     WebsiteApi\CoreBundle\Services\DoctrineAdapter\PdoSessionHandler
        arguments: ['@app.twake_doctrine', {lock_mode: 0}]

    session.handler.cassandra:
        class:     WebsiteApi\CoreBundle\Services\DoctrineAdapter\CassandraSessionHandler
        arguments: ['@app.twake_doctrine', {lock_mode: 0}]

    user.provider.twake:
        class: WebsiteApi\UsersBundle\Repository\UserRepository
        factory: ['@app.twake_doctrine', 'getRepository']
        arguments: ['WebsiteApi\UsersBundle\Entity\User']

    kernel.event_listener.json_request_transformer:
      class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
