globalsearch_event:
  path:       /event
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:ES }


globalsearch_message:
  path:       /message
  defaults: { _controller: TwakeGlobalSearchBundle:Message:ESMessage }


globalsearch_global:
  path:       /global
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:ESGlobal }