globalsearch_quicksearch:
  path:       /quicksearch
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:QuickSearch }

globalsearch_advancedbloc:
  path:       /advancedbloc
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedBloc}

globalsearch_advancedfile:
  path:       /advancedfile
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedFile}

globalsearch_advancedtask:
  path:       /advancedtask
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedTask}

globalsearch_advancedevent:
  path:       /advancedevent
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedEvent}

globalsearch_tag_get:
    path:     /tags/get
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:get}

globalsearch_tag_save:
    path:     /tags/save
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:save }

globalsearch_tag_remove:
    path:     /tags/remove
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:remove }