globalsearch_file:
  path:       /file
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:ES }


globalsearch_message:
  path:       /message
  defaults: { _controller: TwakeGlobalSearchBundle:Message:ESMessage }


globalsearch_quicksearch:
  path:       /quicksearch
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:QuickSearch }

globalsearch_globalmf:
  path:       /globalmf
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:GlobalSearchMF }