globalsearch_file:
  path:       /file
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:ES }


globalsearch_message:
  path:       /message
  defaults: { _controller: TwakeGlobalSearchBundle:Message:ESMessage }


globalsearch_quicksearch:
  path:       /quicksearch
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:QuickSearch }

globalsearch_advancedsearch:
  path:       /advancedsearch
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedSearch }


globalsearch_testindex:
  path:       /testindex
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:TestIndex }

#globalsearch_reindex:
#  path:       /reindex
#  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:Reindex }
#
globalsearch_mapping:
  path:       /mapping
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:Mapping }

globalsearch_pagination:
  path:       /pagination
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:Pagination }
