globalsearch_file:
  path:       /file
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:ES }


globalsearch_message:
  path:       /message
  defaults: { _controller: TwakeGlobalSearchBundle:Message:ESMessage }


globalsearch_quicksearch:
  path:       /quicksearch
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:QuickSearch }

globalsearch_advancedbloc:
  path:       /advancedbloc
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedBloc}

globalsearch_advancedfile:
  path:       /advancedfile
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:AdvancedFile}

globalsearch_testindex:
  path:       /testindex
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:TestIndex }

#globalsearch_reindex:
#  path:       /reindex
#  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:Reindex }
#
globalsearch_mapping:
  path:       /mapping
  defaults: { _controller: TwakeGlobalSearchBundle:GlobalSearch:Mapping }


globalsearch_tag_get:
    path:     /tagget
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:get}

globalsearch_tag_save:
    path:     /tagsave
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:save }

globalsearch_tag_remove:
    path:     /tagremove
    defaults: { _controller: TwakeGlobalSearchBundle:Tag:remove }

