services:

  globalsearch.event:
    class: WebsiteApi\GlobalSearchBundle\Services\Event
    arguments: ["@app.twake_doctrine"]

  globalsearch.message:
    class: WebsiteApi\GlobalSearchBundle\Services\Blocmessage
    arguments: ["@app.twake_doctrine"]

  globalsearch.global:
    class: WebsiteApi\GlobalSearchBundle\Services\Search
    arguments: ["@app.twake_doctrine", "@globalsearch.message", "globalsearch.event"]