services:

  globalsearch.event:
    class: WebsiteApi\GlobalSearchBundle\Services\Event
    arguments: ["@app.twake_doctrine"]

  globalsearch.message:
    class: WebsiteApi\GlobalSearchBundle\Services\Blocmessage
    arguments: ["@app.twake_doctrine"]

  globalsearch.user:
    class: WebsiteApi\UsersBundle\Services\Users
    arguments: ["@app.twake_doctrine"]

  globalsearch.workspace:
    class: WebsiteApi\WorkspacesBundle\Services\Workspaces
    arguments: ["@app.twake_doctrine", "@app.workspace_levels", "@app.workspace_members", "@app.group_managers", "@app.group_apps", "@app.groups", "@app.pricing_plan","@app.string_cleaner","@app.pusher",'@app.workspaces_activities','@app.translate','@app.calendar.calendar','@app.calendar.event','@app.drive.adapter_selector', "@app.workspaces_apps"]

  globalsearch.channel:
    class: WebsiteApi\ChannelsBundle\Services\ChannelsSystem
    arguments: ["@app.twake_doctrine", "@app.messages", "@app.websockets", "@app.applications_api"]

  globalsearch.global:
    class: WebsiteApi\GlobalSearchBundle\Services\Search
    arguments: ["@app.twake_doctrine", "@globalsearch.message", "@globalsearch.event", "@globalsearch.user", "@globalsearch.workspace", "@globalsearch.channel"]