services:

  globalsearch.event:
    class: WebsiteApi\GlobalSearchBundle\Services\Event
    arguments: ["@app.twake_doctrine"]

  globalsearch.message:
    class: WebsiteApi\GlobalSearchBundle\Services\Message
    arguments: ["@app.twake_doctrine"]