administration_api_apps_get_all:
  path: /getApps
  defaults: { _controller: AdministrationApiAppsBundle:Apps:getAllApps}
  methods: [POST]

administration_api_apps_get_one:
  path: /getOneApp
  defaults: { _controller: AdministrationApiAppsBundle:Apps:getOneApp }