services:

    app.group_managers:
        class: WebsiteApi\WorkspacesBundle\Services\GroupManagers
        arguments: ["@doctrine.orm.entity_manager", "@app.twake_mailer"]

    app.groups:
        class: WebsiteApi\WorkspacesBundle\Services\Groups
        arguments: ["@doctrine.orm.entity_manager", "@app.group_managers","@website_api_market.applications","@app.string_cleaner","@app.group_period","@app.workspace_members"]

    app.group_apps:
        class: WebsiteApi\WorkspacesBundle\Services\GroupApps
        arguments: ["@doctrine.orm.entity_manager", "@app.group_managers"]

    app.group_period:
        class: WebsiteApi\WorkspacesBundle\Services\GroupPeriods
        arguments: ["@doctrine.orm.entity_manager"]

    app.pricing_plan:
        class: WebsiteApi\WorkspacesBundle\Services\PricingPlan
        arguments: ["@doctrine.orm.entity_manager","@app.group_period"]

    app.workspace_levels:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspaceLevels
        arguments: ["@doctrine.orm.entity_manager"]

    app.workspace_members:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspaceMembers
        arguments: ["@doctrine.orm.entity_manager", "@app.workspace_levels", "@app.twake_mailer", "@app.string_cleaner","@app.pusher","@app.pricing_plan", "@app.messages_master", "@app.calendars"]

    app.workspaces:
        class: WebsiteApi\WorkspacesBundle\Services\Workspaces
        arguments: ["@doctrine.orm.entity_manager", "@app.workspace_levels", "@app.workspace_members", "@app.group_managers", "@app.group_apps", "@app.workspace_stats","@app.pricing_plan","@app.string_cleaner"]

    app.workspaces_apps:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspacesApps
        arguments: ["@doctrine.orm.entity_manager", "@app.workspace_levels", "@app.group_apps","@app.group_managers"]

    app.workspace_stats:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspaceStats
        arguments: ["@doctrine.orm.entity_manager"]
