services:

    app.group_managers:
        class: WebsiteApi\WorkspacesBundle\Services\GroupManagers
        arguments: ["@app.twake_doctrine", "@app.twake_mailer", "@app.pusher"]

    app.groups:
        class: WebsiteApi\WorkspacesBundle\Services\Groups
        arguments: ["@app.twake_doctrine", "@app.group_managers","@app.applications","@app.string_cleaner","@app.group_period","@app.workspace_members", "@app.pusher"]

    app.group_apps:
        class: WebsiteApi\WorkspacesBundle\Services\GroupApps
        arguments: ["@app.twake_doctrine", "@app.group_managers", "@app.workspaces_apps"]

    app.group_period:
        class: WebsiteApi\WorkspacesBundle\Services\GroupPeriods
        arguments: ["@app.twake_doctrine", "@app.subscription_system"]

    app.pricing_plan:
        class: WebsiteApi\WorkspacesBundle\Services\PricingPlan
        arguments: ["@app.twake_doctrine","@app.group_period"]

    app.workspace_levels:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspaceLevels
        arguments: ["@app.twake_doctrine", "@app.pusher"]

    app.workspace_members:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspaceMembers
        arguments: ["@app.twake_doctrine", "@app.workspace_levels", "@app.twake_mailer", "@app.string_cleaner","@app.pusher","@app.pricing_plan", "@app.calendar.calendar", '@app.workspaces_activities', '@app.group_managers', '@app.channels.channels_system']

    app.workspaces:
        class: WebsiteApi\WorkspacesBundle\Services\Workspaces
        arguments: ["@app.twake_doctrine", "@app.workspace_levels", "@app.workspace_members", "@app.group_managers", "@app.group_apps", "@app.groups", "@app.pricing_plan","@app.string_cleaner","@app.pusher",'@app.workspaces_activities','@app.translate','@app.calendar.calendar','@app.calendar.event','@app.drive.adapter_selector', "@app.workspaces_apps"]

    app.workspaces_activities:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspacesActivities
        arguments: ["@app.twake_doctrine", '@app.applications']

    app.workspaces_apps:
        class: WebsiteApi\WorkspacesBundle\Services\WorkspacesApps
        arguments: ["@app.twake_doctrine", "@app.workspace_levels","@app.group_managers","@app.pusher", "@app.channels.channels_system", "@app.applications_api"]

    groups.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\GroupsTopic
        tags:
            - { name: gos_web_socket.topic }

    workspaces.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\WorkspacesTopic
        tags:
            - { name: gos_web_socket.topic }

    workspaces_users.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\WorkspacesUsersTopic
        tags:
            - { name: gos_web_socket.topic }

    workspaces_apps.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\WorkspacesAppsTopic
        tags:
            - { name: gos_web_socket.topic }

    workspaces_of_user.topic:
        class: WebsiteApi\WorkspacesBundle\Topic\WorkspacesOfUserTopic
        tags:
            - { name: gos_web_socket.topic }
