administration_api_apps_get_all:
  path: /getApps
  defaults: { _controller: AdministrationApiApps:Apps:getAllApps}
  methods: [POST]

administration_api_apps_get_one:
  path: /getOneApp
  defaults: { _controller: AdministrationApiApps:Apps:getOneApp }
  methods: [POST]

administration_api_apps_toggle_validation:
  path: /toggleValidation
  defaults: { _controller: AdministrationApiApps:Apps:toggleValidation }
  methods: [POST]