
twake_user_login_check:
    path:     /login
    defaults: { _controller: TwakeUsersBundle:UsersConnections:login }

twake_user_logout:
    path:     /logout
    defaults: { _controller: TwakeUsersBundle:UsersConnections:logout }


twake_user_get:
    path:     /current/get
    defaults: { _controller: TwakeUsersBundle:UsersConnections:currentUser }