
citi_go_user_login_check:
    path:     /login
    defaults: { _controller: TwakeUsersBundle:Login:loginCheck }

citi_go_user_logout:
    path:     /logout
    defaults: { _controller: TwakeUsersBundle:Login:logout }


citi_go_user_get:
    path:     /current/get
    defaults: { _controller: TwakeUsersBundle:CurrentUser:get }

citi_go_users_current_subscription_set:
    path:     /current/subscription/set
    defaults: { _controller: TwakeUsersBundle:UserSubscription:set }

citi_go_users_subscription_get:
    path:     /subscription/get
    defaults: { _controller: TwakeUsersBundle:UserSubscription:get }

citi_go_user_getnotifications:
    path:     /current/getnotifications
    defaults: { _controller: TwakeUsersBundle:CurrentUser:getnotifications }

citi_go_user_readnotifications:
    path:       /current/readnotifications
    defaults:   {_controller: TwakeUsersBundle:CurrentUser:readnotifications}

citi_go_user_readallnotifications:
    path:       /current/readallnotifications
    defaults:   {_controller: TwakeUsersBundle:CurrentUser:readallnotifications}

citi_go_contact:
    path:     /contacts/{script}
    defaults: { _controller: TwakeUsersBundle:Contact:scripts }





citi_go_user_mailconfirm_override:
    path:     /register/confirm/{token}
    defaults: { _controller: TwakeUsersBundle:Registration:confirm }


citi_go_user_scripts_endsignup_validate:
    path:     /register/end/validate
    defaults: { _controller: TwakeUsersBundle:EndSignUp:validate }

citi_go_user_registration_check_inputs_override:
    path:     /register/check
    defaults: { _controller: TwakeUsersBundle:Registration:check }



citi_go_account_get:
    path:     /account/profile
    defaults: { _controller: TwakeUsersBundle:Account:profile }

citi_go_account_update:
      path:     /account/profile/update
      defaults: { _controller: TwakeUsersBundle:Account:updateProfile }

citi_go_account_updateUserImage:
      path:     /account/profile/update_userimage
      defaults: { _controller: TwakeUsersBundle:Account:updateProfileUserImage }

citi_go_account_updateCoverImage:
      path:     /account/profile/update_coverimage
      defaults: { _controller: TwakeUsersBundle:Account:updateProfileCoverImage }

citi_go_account_parameters:
    path:     /account/parameters
    defaults: { _controller: TwakeUsersBundle:AccountParameters:getParameters }

citi_go_account_parameters_script:
    path:     /account/parameters/script
    defaults: { _controller: TwakeUsersBundle:AccountParameters:script }


citi_go_account_reset_pass:
    path:     /resetPassw
    defaults: { _controller: TwakeUsersBundle:Registration:resetPssw }


citi_go_user_homepage:
    path:     /get
    defaults: { _controller: TwakeUsersBundle:User:index }

citi_go_user_fastSearch:
    path:     /fastSearch
    defaults: { _controller: TwakeUsersBundle:User:fastSearch }

# Blackholes

citi_go_user_blackhole_register:
    path:     /register{trailingSlash}
    defaults: { _controller: TwakeUsersBundle:Registration:blackHole }
    requirements: { trailingSlash : "[/]{0,1}" }

citi_go_user_blackhole_login:
    path:     /login
    defaults: { _controller: TwakeUsersBundle:Registration:blackHole }

citi_go_user_blackhole_login_check:
    path:     /login_check
    defaults: { _controller: TwakeUsersBundle:Registration:blackHole }


#Unused / to change

citi_go_account_testnotifications:
    path:     /testnotif
    defaults: { _controller: TwakeUsersBundle:Notifications:test }

citi_go_account_save:
    path:     /scripts/account/save
    defaults: { _controller: TwakeUsersBundle:Account:ajaxSave }

citi_go_account_orga_list:
    path:     /account/groups{trailingSlash}
    defaults: { _controller: TwakeUsersBundle:AccountOrgaList:index }
    requirements: { trailingSlash : "[/]{0,1}" }

citi_go_account_parameters_scripts:
    path:     /account/parameters/{page}
    defaults: { _controller: TwakeUsersBundle:AccountParameters:parametersPages }

citi_go_account_transactions:
    path:     /account/transactions{trailingSlash}
    defaults: { _controller: TwakeUsersBundle:AccountTransactions:index }
    requirements: { trailingSlash : "[/]{0,1}" }

citi_go_account_contacts:
    path:     /account/contacts{trailingSlash}
    defaults: { _controller: TwakeUsersBundle:AccountContacts:index }
    requirements: { trailingSlash : "[/]{0,1}" }

citi_go_account_contacts_ajax:
    path:     /account/contacts/{script}
    defaults: { _controller: TwakeUsersBundle:Contact:scripts }

citi_go_account_notifications:
    path:     /account/notifications{trailingSlash}
    defaults: { _controller: TwakeUsersBundle:Notifications:index }
    requirements: { trailingSlash : "[/]{0,1}" }



citi_go_user_endsignup:
    path:     /register/end
    defaults: { _controller: TwakeUsersBundle:EndSignUp:index }

citi_go_user_newmailconfirm:
    path:     /account/verifymail
    defaults: { _controller: TwakeUsersBundle:SecondMail:verify }

citi_go_connection_troubleshooting:
    path:     /connection-troubleshooting
    defaults: { _controller: TwakeUsersBundle:Registration:lost }

citi_go_user_check_second_mail:
    path:       /account/verifySecondMail
    defaults:   { _controller: TwakeUsersBundle:SecondMail:verify }


citi_go_notification_setopened:
    path:     /scripts/notifications/open
    defaults: { _controller: TwakeUsersBundle:Notifications:setOpen }

citi_go_notification_setread:
    path:     /scripts/notifications/read
    defaults: { _controller: TwakeUsersBundle:Notifications:setRead }

citi_go_notification_get:
    path:     /scripts/notifications/get
    defaults: { _controller: TwakeUsersBundle:Notifications:getProfile }
