services:

    app.core_remember_me_manager:
        class: WebsiteApi\UsersBundle\Services\RememberMe
        arguments: ["@service_container"]

    app.user:
        class: WebsiteApi\UsersBundle\Services\User
        arguments: ["@doctrine.orm.entity_manager", "@app.pusher", "@security.encoder_factory", "@security.authorization_checker", "@security.token_storage", "@app.core_remember_me_manager", "@event_dispatcher", "@request_stack", "@app.user_stats", "@app.twake_mailer", "@app.string_cleaner", "@app.workspace_members","@app.groups","@app.workspaces","@app.pricing_plan","@circle.restclient"]

    app.user_stats:
        class: WebsiteApi\UsersBundle\Services\UserStats
        arguments: ["@doctrine.orm.entity_manager"]

    app.contacts:
        class: WebsiteApi\UsersBundle\Services\Contacts
        arguments: ["@doctrine.orm.entity_manager", "@app.notifications"]

    app.token_service:
        class: WebsiteApi\UsersBundle\Services\TokenService
        arguments: ["@doctrine.orm.entity_manager"]

    ping.rpc:
        class: WebsiteApi\UsersBundle\Topic\PingTopic
        tags:
            - { name: gos_web_socket.rpc }