services:

    app.core_remember_me_manager:
        class: WebsiteApi\UsersBundle\Services\RememberMe
        arguments: ["@service_container"]

    app.user:
        class: WebsiteApi\UsersBundle\Services\User
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory", "@security.authorization_checker", "@security.token_storage", "@app.core_remember_me_manager", "@event_dispatcher", "@request_stack", "@app.user_stats", "@app.twake_mailer", "@app.string_cleaner", "@app.workspace_members"]

    app.user_stats:
        class: WebsiteApi\UsersBundle\Services\UserStats
        arguments: ["@doctrine.orm.entity_manager"]

    echo.topic:
        class: WebsiteApi\UsersBundle\Topic\EchoTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: ["@gos_web_socket.websocket.client_manipulator"]
