services:

    app.core_remember_me_manager:
        class: WebsiteApi\UsersBundle\Services\RememberMe
        arguments: ["@service_container"]

    app.users:
        class: WebsiteApi\UsersBundle\Services\Users
        arguments: ["@app.twake_doctrine"]

    app.user:
        class: WebsiteApi\UsersBundle\Services\User
        arguments: ["@app.twake_doctrine", "@app.pusher", "@security.encoder_factory", "@security.authorization_checker", "@security.token_storage", "@app.core_remember_me_manager", "@event_dispatcher", "@request_stack", "@app.twake_mailer", "@app.string_cleaner", "@app.workspace_members","@app.groups","@app.workspaces","@app.pricing_plan","@circle.restclient","@app.translate", "%STANDALONE%", "%LICENCE_KEY%","@circle.restclient",]

    app.user_updates:
        class: WebsiteApi\UsersBundle\Services\Updates
        arguments: []