connections_topic:
    channel: connections/{id_user}
    handler:
        callback: 'connections.topic' #related to the getName() of your topic
    requirements:
         id_user:
            pattern: "[0-9]+"

ping_rpc:
    channel: ping/{method}
    handler:
        callback: 'ping.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !