twake_workspaces_get:
    path:     /get
    defaults: { _controller: Twake\Workspaces:Workspace:get }

twake_workspaces_get_public_data:
    path:     /get_public_data
    defaults: { _controller: Twake\Workspaces:Workspace:getPublicData }

twake_workspaces_create:
    path:     /create
    defaults: { _controller: Twake\Workspaces:Workspace:create }

twake_workspaces_duplicate:
    path:     /duplicate
    defaults: { _controller: Twake\Workspaces:Workspace:duplicate }

twake_workspaces_delete:
    path:     /delete
    defaults: { _controller: Twake\Workspaces:Workspace:delete }

twake_workspaces_archive_workspace:
    path:     /archive
    defaults: { _controller: Twake\Workspaces:Workspace:archiveWorkspace }

twake_workspaces_unarchive_workspace:
    path:     /unarchive
    defaults: { _controller: Twake\Workspaces:Workspace:unarchiveWorkspace }

twake_workspaces_hide_or_unhide_workspace:
    path:     /hideOrNot
    defaults: { _controller: Twake\Workspaces:Workspace:hideOrUnhideWorkspace }

twake_workspaces_favorite_or_unfavorite_workspace:
    path:     /favorite
    defaults: { _controller: Twake\Workspaces:Workspace:favoriteOrUnfavoriteWorkspace }

twake_workspaces_have_notifications_or_not_workspace:
    path:     /notifications
    defaults: { _controller: Twake\Workspaces:Workspace:haveNotificationsOrNotWorkspace }

twake_workspaces_set_isNew:
    path:     /set/isNew
    defaults: { _controller: Twake\Workspaces:Workspace:setIsNew }

# Edit workspace data

twake_workspaces_get_data:
    path:     /data/details
    defaults: { _controller: Twake\Workspaces:WorkspaceData:getDetails }

twake_workspaces_set_name:
    path:     /data/name
    defaults: { _controller: Twake\Workspaces:WorkspaceData:setName }

twake_workspaces_set_logo:
    path:     /data/logo
    defaults: { _controller: Twake\Workspaces:WorkspaceData:setLogo }

twake_workspaces_set_wallpaper:
    path:     /data/wallpaper
    defaults: { _controller: Twake\Workspaces:WorkspaceData:setWallpaper }

twake_workspaces_get_by_name:
    path:     /getByName
    defaults: { _controller: Twake\Workspaces:Workspace:getWorkspaceByName }

# Apps

twake_workspaces_get_module_apps:
    path:     /apps/getModuleApps
    defaults: { _controller: Twake\Workspaces:Workspace:getModuleApps }

twake_workspaces_get_apps:
    path:     /apps/get
    defaults: { _controller: Twake\Workspaces:Workspace:getApps }

twake_workspaces_enable_app:
    path:     /apps/enable
    defaults: { _controller: Twake\Workspaces:Workspace:enableApp }

twake_workspaces_disable_app:
    path:     /apps/disable
    defaults: { _controller: Twake\Workspaces:Workspace:disableApp }


# Groups
twake_groups_get_users:
    path:     /group/getUsers
    defaults: { _controller: Twake\Workspaces:Group:getUsers }

twake_groups_edit_user:
    path:     /group/edit
    defaults: { _controller: Twake\Workspaces:Group:editUser }

twake_groups_remove_user:
    path:     /group/removeUser
    defaults: { _controller: Twake\Workspaces:Group:removeUser }

twake_groups_set_name:
    path:     /group/data/name
    defaults: { _controller: Twake\Workspaces:Group:changeName }

twake_groups_set_logo:
    path:     /group/data/logo
    defaults: { _controller: Twake\Workspaces:Group:setLogo }

twake_groups_get_workspaces:
    path:     /group/getWorkspaces
    defaults: { _controller: Twake\Workspaces:Group:getWorkspaces }

twake_groups_run_free_offer:
    path:     /group/freeOffer
    defaults: { _controller: Twake\Workspaces:Group:runFreeOffer }

twake_groups_use_apps:
    path:     /group/app/use
    defaults: { _controller: Twake\Workspaces:GroupApps:useApp }

twake_groups_get_apps:
    path:     /group/apps/get
    defaults: { _controller: Twake\Workspaces:GroupApps:getApps }

twake_groups_set_workspace_default:
    path:     /group/workspacedefault/set
    defaults: { _controller: Twake\Workspaces:GroupApps:setWorkspaceDefault }

twake_groups_force_application:
    path:     /group/application/force
    defaults: { _controller: Twake\Workspaces:GroupApps:forceApplication }

twake_groups_remove_application:
    path:     /group/application/remove
    defaults: { _controller: Twake\Workspaces:GroupApps:removeApplication }

twake_groups_manager_get:
    path:     /group/manager/get
    defaults: { _controller: Twake\Workspaces:GroupManager:getManagers }

twake_groups_manager_add:
    path:     /group/manager/add
    defaults: { _controller: Twake\Workspaces:GroupManager:addManagers }

twake_groups_manager_remove:
    path:     /group/manager/remove
    defaults: { _controller: Twake\Workspaces:GroupManager:removeManagers }

twake_groups_manager_edit:
    path:     /group/manager/edit
    defaults: { _controller: Twake\Workspaces:GroupManager:editManagers }

twake_groups_manager_toggle:
    path:     /group/manager/toggleManager
    defaults: { _controller: Twake\Workspaces:GroupManager:toggleManager }


# Edit members

twake_workspaces_members_list:
    path:     /members/list
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:getMembers }

twake_workspaces_members_addlist:
    path:     /members/addlist
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:addList }

twake_workspaces_members_removemail:
    path:     /members/removemail
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:removeMail }

twake_workspaces_members_remove:
    path:     /members/remove
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:removeMembers }

twake_workspaces_members_changelevel:
    path:     /members/changelevel
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:changeMembersLevel }

#Levels

twake_workspaces_levels_list:
    path:     /levels/list
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:getLevels }

twake_workspaces_levels_create:
    path:     /levels/create
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:createLevel }

twake_workspaces_levels_delete:
    path:     /levels/delete
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:deleteLevel }

twake_workspaces_levels_edit:
    path:     /levels/edit
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:editLevel }

twake_workspaces_levels_default:
    path:     /levels/default
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:makeDefaulLevel }

twake_workspaces_levels_get_by_label:
    path:     /levels/getByLabel
    defaults: { _controller: Twake\Workspaces:WorkspaceLevels:getByLabel }

twake_workspaces_members_get_workspaces:
    path:     /members/getWorkspaces
    defaults: { _controller: Twake\Workspaces:WorkspaceMembers:getWorkspaces }
