services:
    app.channels.direct_messages_system:
            class: Twake\Channels\Services\DirectMessagesSystem
            arguments: ["@app.twake_doctrine", "@app.messages", "@app.applications_api","@app.workspace_members"]

    app.channels.channels_system:
            class: Twake\Channels\Services\ChannelsSystem
            arguments: ["@app.twake_doctrine", "@app.messages", "@app.websockets", "@app.applications_api", "@app.workspace_members", "@app.accessmanager"]

    app.channels.notifications:
            class: Twake\Channels\Services\ChannelsNotificationsSystem
            arguments: [ "@app.twake_doctrine", "@app.notifications", "@app.pusher","@app.workspace_members"]