administration_api_groups_get_all:
  path: /getGroups
  defaults: { _controller: AdministrationApiWorkspacesBundle:Groups:getAllGroups }
  methods: [POST]

administration_api_groups_get_one:
  path: /getOneGroup
  defaults: { _controller: AdministrationApiWorkspacesBundle:Groups:getOneGroup }
  methods: [POST]

administration_api_workspaces_get_one:
  path: /getWorkspace
  defaults: { _controller: AdministrationApiWorkspacesBundle:Workspaces:getOneWorkspace }
  methods: [POST]