administration_api_groups_get_all:
  path: /getGroups
  defaults: { _controller: AdministrationApiWorkspacesBundle:Groups:getAllGroups }
  methods: [POST]

administration_api_groups_get_one:
  path: /getOneGroup
  defaults: { _controller: AdministrationApiWorkspacesBundle:Groups:getOneGroup }
  methods: [POST]

administration_api_workspaces_get_all:
  path: /getAllWorkspaces
  defaults: { _controller: AdministrationApiWorkspacesBundle:Workspaces:getAllWorkspaces }
  methods: [POST]

administration_api_workspaces_get_one:
  path: /getWorkspace
  defaults: { _controller: AdministrationApiWorkspacesBundle:Workspaces:getOneWorkspace }
  methods: [POST]

administration_api_groups_find:
  path: /searchGroups
  defaults: { _controller: AdministrationApiWorkspacesBundle:Groups:findGroups }