services:

  administration.groups:
    class: AdministrationApi\WorkspacesBundle\Services\AdministrationGroups
    arguments: [ "@app.twake_doctrine" ]

  administration.workspaces:
    class: AdministrationApi\WorkspacesBundle\Services\AdministrationWorkspaces
    arguments: [ "@app.twake_doctrine" ]