#Remote want to send a mail or a push notification
from_remote_mail:
    path:     /mail
    defaults: { _controller: TwakeCoreBundle:Remote:mail }

from_remote_push:
    path:     /push
    defaults: { _controller: TwakeCoreBundle:Remote:push }


from_remote_recaptcha:
    path:     /recaptcha
    defaults: { _controller: TwakeCoreBundle:Remote:verifyReCaptcha }
