services:

    app.twake_mailer:
        class: WebsiteApi\CoreBundle\Services\TwakeMailer
        arguments: ["@mailer", "@templating", "%MAIL_FROM%", "%SERVER_NAME%", "%STANDALONE%", "%LICENCE_KEY%", "@circle.restclient"]

    app.pusher:
        class: WebsiteApi\CoreBundle\Services\ZMQPusher
        arguments: ["%websocket_pusher_remote_host%", "%websocket_pusher_port%", "@app.twake_doctrine"]

    app.translate:
        class: WebsiteApi\CoreBundle\Services\Translate
        arguments: []

    app.twake_doctrine:
        class: WebsiteApi\CoreBundle\Services\DoctrineAdapter\ManagerAdapter
        arguments: ["@doctrine.orm.entity_manager", "%database_driver%", "%database_host%", "%database_port%", "%database_user%", "%database_password%", "%database_dbname%"]

    websocket.pdo.ping:
        class: WebsiteApi\CoreBundle\Services\PDOPinger

    websocket.command:
        class: WebsiteApi\CoreBundle\Command\WebsocketServerCommand
        arguments:
            - '@gos_web_socket.entry_point'
            - '%web_socket_server.host%'
            - '%web_socket_server.port%'
            - '@?monolog.logger.websocket'
        tags:
            - { name: console.command, command: twake:websocket:run }
