services:

    app.twake_mailer:
        class: WebsiteApi\CoreBundle\Services\TwakeMailer
        arguments: ["@mailer", "@templating", "%MAIL_FROM%", "%SERVER_NAME%", "%STANDALONE%", "%LICENCE_KEY%", "@circle.restclient"]

    app.pusher:
        class: WebsiteApi\CoreBundle\Services\ZMQPusher
        arguments: ["%websocket_pusher_remote_host%", "%websocket_pusher_port%", "@doctrine.orm.entity_manager"]

    app.translate:
        class: WebsiteApi\CoreBundle\Services\Translate
        arguments: []

    websocket.pdo.ping:
        class: WebsiteApi\CoreBundle\Services\PDOPinger
