ping_rpc:
    channel: ping/{method}
    handler:
        callback: 'ping.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !

collections_topic:
    channel: "{id}"
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"