ping_rpc:
    channel: ping/{method}
    handler:
        callback: 'ping.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !

collections_topic:
    channel: collections/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

notifications_topic:
    channel: notifications/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

workspace_users_topic:
    channel: workspace_users/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

workspaces_of_user_topic:
    channel: workspaces_of_user/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

workspace_topic:
    channel: workspace/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

workspace_apps_topic:
    channel: workspace_apps/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

group_topic:
    channel: group/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"

users_topic:
    channel: users/{id}
    handler:
        callback: 'collections.topic'
    requirements:
        id:
            pattern: ".+"