services:
    app.images_modifiers:
        class: WebsiteApi\UploadBundle\Services\ImagesModifiers

    app.upload:
        class: WebsiteApi\UploadBundle\Services\Upload
        arguments: ["@app.images_modifiers"]

    app.uploader:
        class: WebsiteApi\UploadBundle\Services\Uploader
        arguments: ["@doctrine.orm.entity_manager", "@app.upload", "@app.images_modifiers"]

    #AWS
    app.aws_uploader:
        class: WebsiteApi\UploadBundle\Services\AWS_Uploader
        arguments: [%aws%, "@doctrine.orm.entity_manager", "@app.upload", "@app.images_modifiers"]
