developers_api_v1_workspace_getInfoApp:
    path:     application
    defaults: { _controller: DevelopersApiV1WorkspacesBundle:Workspaces:getInfoApp }
    methods: [GET]

developers_api_v1_workspace_getMembers:
    path:     workspace/{workspace_id}/members
    defaults: { _controller: DevelopersApiV1WorkspacesBundle:Workspaces:getMembers }
    methods: [GET]
    requirements:
            workspace_id: '\d+'

developers_api_v1_workspace_getListLevels:
    path:     workspace/{workspace_id}/levels
    defaults: { _controller: DevelopersApiV1WorkspacesBundle:Workspaces:getListLevels }
    methods: [GET]
    requirements:
            workspace_id: '\d+'


developers_api_v1_workspace_get_member:
    path:     workspace/{workspace_id}/member/{id}
    defaults: { _controller: DevelopersApiV1WorkspacesBundle:Workspaces:getMemberLevel }
    methods: [GET]
    requirements:
        workspace_id: '\d+'
        id : '\d+'
