#twake_calls_create:
#    path:     /create
#    defaults: { _controller: TwakeCallsBundle:Calls:create }


objectLinks_create:
    path:     /objectLinks/create
    defaults: { _controller: TwakeObjectLinksBundle:ObjectLinks:createLink }
    methods: [POST]
