services:

  globalsearch.quicksearch:
    class: Twake\GlobalSearch\Services\QuickSearch
    arguments: ["@app.twake_doctrine", "@app.users", "@app.workspaces", "@app.channels.channels_system", "@globalsearch.advancedfile", "@app.workspace_members", "@globalsearch.messagebloc"]

  globalsearch.advancedbloc:
    class: Twake\GlobalSearch\Services\AdvancedBloc
    arguments: ["@app.twake_doctrine", "@globalsearch.messagebloc", "@app.workspaces"]

  globalsearch.advancedfile:
    class: Twake\GlobalSearch\Services\AdvancedFile
    arguments: ["@app.twake_doctrine","@app.workspaces"]

  globalsearch.advancedtask:
    class: Twake\GlobalSearch\Services\AdvancedTask
    arguments: ["@app.twake_doctrine", "@app.workspaces"]

  globalsearch.advancedevent:
    class: Twake\GlobalSearch\Services\AdvancedEvent
    arguments: ["@app.twake_doctrine", "@app.workspaces"]

  globalsearch.messagebloc:
    class: Twake\GlobalSearch\Services\Blocmessage
    arguments: ["@app.twake_doctrine"]

  globalsearch.reindex:
    class: Twake\GlobalSearch\Services\Reindex
    arguments: ["@app.twake_doctrine"]

  globalsearch.mapping:
    class: Twake\GlobalSearch\Services\Mapping

  globalsearch.pagination:
    class: Twake\GlobalSearch\Services\Pagination
    arguments: ["@app.twake_doctrine"]

  globalsearch.tag:
      class: Twake\GlobalSearch\Services\Tag
      arguments: ["@app.twake_doctrine", "@app.accessmanager"]