version: "2"

services:
  scylladb:
    image: scylladb/scylla
    ports:
      - 9180:9180
      - 9100:9100
      - 9160:9160
      - 9042:9042
    volumes:
      - ./docker-data/scylladb:/var/lib/scylla
    command: "--experimental 1"
  php:
    image: twaketech/twake-php
    volumes:
      - ./docker/cron:/cron
      - ./backend/core/:/twake-core:cached
      - ./docker-data/fpm/:/etc/docker-data/fpm/
    depends_on:
      - scylladb
    links:
      - scylladb
