event_create:
    path: workspace/{workspace_id}/calendar/event/{calendar_id}
    methods: [POST]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:createEvent }
    requirements:
        workspace_id: "[0-9]+"
        calendar_id: "[0-9]+"

calendar_create:
    path: workspace/{workspace_id}/calendar
    methods: [POST]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:createCalendar }
    requirements:
        workspace_id: "[0-9]+"

calendar_display:
    path: workspace/{workspace_id}/calendar/{calendar_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:getCalendar }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"

calendar_all_display:
    path: workspace/{workspace_id}/calendar/all
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:getAllCalendar }
    requirements:
          workspace_id: "[0-9]+"

event_display:
    path: workspace/{workspace_id}/calendar/event/{event_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:getEvent }
    requirements:
          event_id: "[0-9]+"
          workspace_id: "[0-9]+"

event_all_display:
    path: workspace/{workspace_id}/calendar/{calendar_id}/event/all
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:getAllEvent }
    requirements:
          workspace_id: "[0-9]+"
          calendar_id: "[0-9]+"

calendar_edit:
    path: workspace/{workspace_id}/calendar/{calendar_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:editCalendar }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"

event_edit:
    path: workspace/{workspace_id}/calendar/event/{event_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:editEvent }
    requirements:
          event_id: "[0-9]+"
          workspace_id: "[0-9]+"

calendar_delete:
    path: workspace/{workspace_id}/calendar/{calendar_id}
    methods: [DELETE]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:deleteCalendar }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"


event_delete:
    path: workspace/{workspace_id}/calendar/{calendar_id}/event/{event_id}
    methods: [DELETE]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:deleteEvent }
    requirements:
          event_id: "[0-9]+"
          workspace_id: "[0-9]+"
          calendar_id: "[0-9]+"

calendar_share:
    path: workspace/{workspace_id}/{other_workspace_id}/calendar/share/{calendar_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:share }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"
          other_workspace_id: "[0-9]+"

calendar_unshare:
    path: workspace/{workspace_id}/{other_workspace_id}/calendar/unshare/{calendar_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:unshare }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"
          other_workspace_id: "[0-9]+"

event_share:
    path: workspace/{workspace_id}/calendar/share/{calendar_id}/event/{event_id}/{user_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:share }
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"
          event_id: "[0-9]+"
          user_id: "[0-9]+"

event_unshare:
    path: workspace/{workspace_id}/calendar/unshare/{calendar_id}/event/{event_id}/{user_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:unshare}
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"
          event_id: "[0-9]+"
          user_id: "[0-9]+"

event_export:
    path: workspace/{workspace_id}/calendar/event/export/{event_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Event:generateIcsFile}
    requirements:
          event_id: "[0-9]+"
          workspace_id: "[0-9]+"

calendar_export:
    path: workspace/{workspace_id}/calendar/export/{calendar_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1CalendarBundle:Calendar:generateIcsFile}
    requirements:
          calendar_id: "[0-9]+"
          workspace_id: "[0-9]+"

calendar_iport:
  path: workspace/{workspace_id}/calendar/import/{calendar_id}
  methods: [GET]
  defaults: {_controller: DevelopersApiV1CalendarBundle:Calendar:parseCalendar}
  requirements:
      workspace_id: "[0-9]+"
      calendar_id: "[0-9]+"