message_init:
    path:     /init
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getInitialisation}

channels_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getChannels }

