#DiscussionController
message_get_stream:
    path:     /getStream
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getStream}

message_get:
    path:     /getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getMessage}

message_search:
    path:     /searchMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:searchMessage}

message_get_drive_message:
    path:     /getDriveMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getDriveMessage}

streams_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getStreams }

streams_mute:
    path:     /streams/mute
    defaults: { _controller: TwakeDiscussionBundle:Discussion:mute }

subjectList_get:
    path:     /subject/getList
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubject }

subject_get_message:
    path:     /subject/getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubjectMessage }

subject_get_last_messages:
    path:     /getLastMessages
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getLastMessages }

#MessageReadController
message_read:
    path:     /read
    defaults: { _controller: TwakeDiscussionBundle:MessageRead:readMessage}

message_read_all:
    path:     /readAll
    defaults: { _controller: TwakeDiscussionBundle:MessageRead:readAllMessages}

