message_init:
    path:     /getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getMessage}

channels_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getChannels }

subjectList_get:
    path:     /subject/getList
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubject }

subject_get_message:
    path:     /subject/getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubjectMessage }

