message_get:
    path:     /getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getMessage}


message_search:
    path:     /searchMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:searchMessage}

message_read:
    path:     /read
    defaults: { _controller: TwakeDiscussionBundle:MessageRead:readMessage}


stream_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getStream }

subjectList_get:
    path:     /subject/getList
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubject }

subject_get_message:
    path:     /subject/getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubjectMessage }

