#DiscussionController
messages_get_stream:
    path:     /getStream
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getStream}

messages_get:
    path:     /getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getMessage}

messages_search:
    path:     /searchMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:searchMessage}

messages_get_drive_message:
    path:     /getDriveMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getDriveMessage}

streams_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getStreams }

streams_mute:
    path:     /streams/mute
    defaults: { _controller: TwakeDiscussionBundle:Discussion:mute }

streams_add:
    path:     /streams/add
    defaults: { _controller: TwakeDiscussionBundle:Discussion:addStream }

streams_remove:
    path:     /streams/remove
    defaults: { _controller: TwakeDiscussionBundle:Discussion:removeStream }

streams_edit:
    path:     /streams/edit
    defaults: { _controller: TwakeDiscussionBundle:Discussion:editStream }

subjectList_get:
    path:     /subject/getList
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubject }

subject_get_message:
    path:     /subject/getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getSubjectMessage }

subject_get_last_messages:
    path:     /getLastMessages
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getLastMessages }

#MessageReadController
messages_read:
    path:     /read
    defaults: { _controller: TwakeDiscussionBundle:MessageRead:readMessage}

messages_read_all:
    path:     /readAll
    defaults: { _controller: TwakeDiscussionBundle:MessageRead:readAllMessages}

