message_init:
    path:     /getMessage
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getMessage}

channels_get:
    path:     /streams/get
    defaults: { _controller: TwakeDiscussionBundle:Discussion:getChannels }

