services:
    app.messages:
            class: WebsiteApi\DiscussionBundle\Services\MessageSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker', "@app.command_executor", '@app.pusher','@app.workspace_levels','@app.drive.FileSystem', '@app.messagesNotificationsCenter', '@app.user_stats', '@app.workspace_stats']

    app.streamSystem:
            class: WebsiteApi\DiscussionBundle\Services\StreamSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker','@app.pusher', '@app.contacts', '@app.workspace_levels', '@app.workspace_members','@app.messagesNotificationsCenter','@app.callSystem',"@app.messages"]

    app.subjectSystem:
            class: WebsiteApi\DiscussionBundle\Services\SubjectSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker','@app.pusher','@app.workspace_levels','@app.messages']

    app.messagesNotificationsCenter:
            class: WebsiteApi\DiscussionBundle\Services\MessagesNotificationsCenter
            arguments: [ "@doctrine.orm.entity_manager","@app.notifications",'@app.pusher', "@app.workspaces"]


    discussion.topic:
          class: WebsiteApi\DiscussionBundle\Topic\DiscussionTopic
          tags:
              - { name: gos_web_socket.topic }
          arguments: ["@app.messages","@app.subjectSystem" , "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager", "@app.notifications"]

    discussion.notifications.topic:
          class: WebsiteApi\DiscussionBundle\Topic\NotificationsCenterTopic
          tags:
              - { name: gos_web_socket.topic }
          arguments: ["@app.streamSystem", "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager"]

    discussionspace.topic:
          class: WebsiteApi\DiscussionBundle\Topic\DiscussionSpaceTopic
          tags:
              - { name: gos_web_socket.topic }
          arguments: ["@app.streamSystem", "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager"]
