services:
    app.messages:
            class: WebsiteApi\DiscussionBundle\Services\MessageSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker', "@app.command_executor", '@gos_web_socket.zmq.pusher','@app.workspace_levels','@app.drive.FileSystem','@app.notifications', '@app.user_stats', '@app.workspace_stats']

    app.streamSystem:
            class: WebsiteApi\DiscussionBundle\Services\StreamSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker','@gos_web_socket.zmq.pusher', '@app.contacts', '@app.workspace_levels', '@app.workspace_members','@app.messageReadSystem','@app.callSystem',"@app.messages"]

    app.subjectSystem:
            class: WebsiteApi\DiscussionBundle\Services\SubjectSystem
            arguments: ["@app.string_cleaner", "@doctrine.orm.entity_manager", '@security.authorization_checker','@gos_web_socket.zmq.pusher','@app.workspace_levels','@app.messages']

    app.messageReadSystem:
            class: WebsiteApi\DiscussionBundle\Services\MessageReadSystem
            arguments: [ "@doctrine.orm.entity_manager", "@app.messages","@app.notifications" ]


    discussion.topic:
          class: WebsiteApi\DiscussionBundle\Topic\DiscussionTopic
          tags:
              - { name: gos_web_socket.topic }
          arguments: ["@app.messages","@app.subjectSystem" , "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager", "@app.notifications"]

    discussionspace.topic:
          class: WebsiteApi\DiscussionBundle\Topic\DiscussionSpaceTopic
          tags:
              - { name: gos_web_socket.topic }
          arguments: ["@app.streamSystem", "@gos_web_socket.websocket.client_manipulator", "@doctrine.orm.entity_manager",]
