discussion_topic:
    channel: discussion/{id}
    handler:
        callback: 'discussion.topic'
    requirements:
        id:
            pattern: "[a-zA-Z0-9-]+"

discussion_notifications_topic:
    channel: discussion_notifications/{user_id}/{workspace_id}
    handler:
        callback: 'discussion.notifications.topic'
    requirements:
        user_id:
            pattern: "[a-zA-Z0-9-]+"
        workspace_id:
            pattern: "[a-zA-Z0-9-]*"

discussionspace_topic:
    channel: discussionspace/{key}
    handler:
        callback: 'discussionspace.topic'
    requirements:
        key:
            pattern: "[a-zA-Z0-9-]+"