discussion_topic:
    channel: discussion/{key}
    handler:
        callback: 'discussion.topic'
    requirements:
        key:
            pattern: "[0-9]+(_[0-9]+)?"

discussionspace_topic:
    channel: discussionspace/{key}
    handler:
        callback: 'discussionspace.topic'
    requirements:
        key:
            pattern: "[0-9]+"