discussion_topic:
    channel: discussion/{key}
    handler:
        callback: 'discussion.topic'
    requirements:
        key:
            pattern: "[a-z]-[a-zA-Z0-9_]+"

discussionspace_topic:
    channel: discussionspace/{key}
    handler:
        callback: 'discussionspace.topic'
    requirements:
        key:
            pattern: "[0-9]+"