discussion_topic:
    channel: discussion/{key}
    handler:
        callback: 'discussion.topic'
    requirements:
        key:
            pattern: "[a-z]-[a-zA-Z0-9_]+"

discussion_notifications_topic:
    channel: discussion_notifications/{user_id}/{stream_id}
    handler:
        callback: 'discussion.notifications.topic'
    requirements:
        user_id:
            pattern: "[0-9]+"
        stream_id:
            pattern: "[0-9]*"

discussionspace_topic:
    channel: discussionspace/{key}
    handler:
        callback: 'discussionspace.topic'
    requirements:
        key:
            pattern: "[0-9]+"