website_api_app_get:
    path:     /app/get
    defaults: { _controller: TwakeMarketBundle:Application:get }

website_api_app_getapps:
    path:     /app/getapps
    defaults: { _controller: TwakeMarketBundle:Application:getapps }

website_api_app_get_app_by_name:
    path:     /app/getAppByPublicKey
    defaults: { _controller: TwakeMarketBundle:Application:getAppByPublicKey }

website_api_app_create:
    path:     /app/create
    defaults: { _controller: TwakeMarketBundle:Application:create }

website_api_app_get_by_cat:
    path:     /app/getAppsByCategory
    defaults: { _controller: TwakeMarketBundle:Application:getByCategory }

website_api_app_add_app:
    path:     /app/add/application
    defaults: { _controller: TwakeMarketBundle:Application:addApp }

website_api_app_add_free_app:
    path:     /app/add/freeApplication
    defaults: { _controller: TwakeMarketBundle:Application:addFreeApp }


website_api_cat_get:
    path:     /category/get
    defaults: { _controller: TwakeMarketBundle:Application:getCategory }


website_api_url_getinfo:
    path:     /url/test
    defaults: { _controller: TwakeMarketBundle:Url:testUrl }

website_api_get_data_token:
    path:     /token
    defaults: { _controller: TwakeMarketBundle:DataToken:makeToken }


## Old code ?


developers_api_users_gettoken:
    path:     /user/gettoken
    defaults: { _controller: TwakeMarketBundle:Application:getUserToken }


website_api_app_acquire:
    path:     /group/acquire
    defaults: { _controller: TwakeMarketBundle:AppUsers:acquire }

website_api_app_remove:
    path:     /group/remove
    defaults: { _controller: TwakeMarketBundle:AppUsers:remove }


website_api_app_vote:
    path:     /user/vote
    defaults: { _controller: TwakeMarketBundle:AppUsers:vote }