twake_applications_create:
    path:     /app/create
    defaults: { _controller: TwakeMarketBundle:Application:create }

twake_applications_remove:
    path:     /app/remove
    defaults: { _controller: TwakeMarketBundle:Application:remove }

twake_applications_update:
    path:     /app/update
    defaults: { _controller: TwakeMarketBundle:Application:update }

twake_applications_get_developed:
    path:     /app/get_developed
    defaults: { _controller: TwakeMarketBundle:Application:getGroupDevelopedApps }