services:

    app.applications:
        class: WebsiteApi\MarketBundle\Services\MarketApplication
        arguments: ["@app.twake_doctrine", "@app.group_managers","@app.pricing_plan"]

    app.applications_api:
        class: WebsiteApi\MarketBundle\Services\ApplicationApi
        arguments: ["@app.twake_doctrine", "@circle.restclient"]

    website_api_market.data_token:
        class: WebsiteApi\MarketBundle\Services\DataTokenSystem
        arguments: ["@app.twake_doctrine"]