
administration_authentication_authenticate:
    path: /authenticate
    defaults: {_controller: AdministrationAuthenticationBundle:Default:authenticate}

administration_authentication_currentUser:
    path: /currentUser
    defaults: {_controller: AdministrationAuthenticationBundle:Default:currentUser}

administration_authentication_addUser:
  path: /addUser
  defaults: {_controller: AdministrationAuthenticationBundle:AdminManager:addUser}


administration_authentication_removeUser:
  path: /removeUser
  defaults: {_controller: AdministrationAuthenticationBundle:AdminManager:removeUser}


administration_authentication_updateUser:
  path: /updateUser
  defaults: {_controller: AdministrationAuthenticationBundle:AdminManager:updateUser}


administration_authentication_listUserAdmin:
  path: /listUserAdmin
  defaults: {_controller: AdministrationAuthenticationBundle:AdminManager:listUserAdmin}


administration_users_listTwakeUsers:
   path: /listTwakeUsers
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:listTwakeUsers}


administration_users_getInfoUser:
   path: /getInfoUser
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:getInfoUser}

administration_users_getUserApp:
   path: /getUserApp
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:getUserApp}

administration_users_setBanned:
   path: /setBanned
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:setBanned}

administration_stats_getSizeUploadedByUser:
    path: /getSizeUploadedByUser
    defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:getSizeUploadedByUser}

administration_users_searchUser:
   path: /searchUser
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeUserManager:searchUser}


administration_groups_listTwakeGroups:
   path: /listTwakeGroups
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeGroupManager:listTwakeGroups}


administration_groups_getInfoWorkspace:
   path: /getInfoWorkspace
   defaults: {_controller: AdministrationAuthenticationBundle:TwakeGroupManager:getInfoWorkspace}

administration_groups_searchWorkspace:
    path: /searchWorkspace
    defaults: {_controller: AdministrationAuthenticationBundle:TwakeGroupManager:searchWorkspace}

administration_groups_sizeWorkspace:
    path: /sizeWorkspace
    defaults: {_controller: AdministrationAuthenticationBundle:TwakeGroupManager:sizeWorkspace}

administration_groups_getWorkspaceMembers:
    path: /getWorkspaceMembers
    defaults: {_controller: AdministrationAuthenticationBundle:TwakeGroupManager:getWorkspaceMembers}

administration_stats_numberOfUserCurrentlyConnected:
    path: /numberOfUserCurrentlyConnected
    defaults: {_controller: AdministrationAuthenticationBundle:Statistics:numberOfUserCurrentlyConnected}

administration_stats_numberOfUsers:
    path: /numberOfUsers
    defaults: {_controller: AdministrationAuthenticationBundle:Statistics:numberOfUsers}

administration_stats_numberOfAppUser:
    path: /numberOfAppUser
    defaults: {_controller: AdministrationAuthenticationBundle:Statistics:numberOfAppUser}

administration_stats_numberOfWorkspaceByApp:
    path: /numberOfWorkspaceByApp
    defaults: {_controller: AdministrationAuthenticationBundle:Statistics:numberOfWorkspaceByApp}

administration_stats_numberOfExtensions:
    path: /numberOfExtensions
    defaults: {_controller: AdministrationAuthenticationBundle:Statistics:numberOfExtensions}

administration_stats_countDailyMessage:
    path: /countDailyMessage
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:countDailyMessage}

administration_stats_numberOfMessagePrivateByUserByWorkspace:
    path: /numberOfMessagePrivateByUserByWorkspace
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:numberOfMessagePrivateByUserByWorkspace}

administration_stats_numberOfMessagePublicByWorkspace:
    path: /numberOfMessagePublicByWorkspace
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:numberOfMessagePublicByWorkspace}

administration_connection_findConnection:
    path: /findConnection
    defaults: {_controller: AdministrationAuthenticationBundle:UserConnection:findConnection}

administration_stats_countPublicMessage:
    path: /countPublicMessage
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:countPublicMessage}

administration_stats_countPrivateMessage:
    path: /countPrivateMessage
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:countPrivateMessage}

administration_stats_numberOfMessagePublicByWorkspace:
    path: /numberOfMessagePublicByWorkspace
    defaults: {_controller: AdministrationAuthenticationBundle:MessageStats:numberOfMessagePublicByWorkspace}
