#Calendar routing
developers_api_v1_drive_remove_drive:
    path:     /remove
    defaults: { _controller: DevelopersApiV1Drive:Drive:remove }
    methods: [POST]

developers_api_v1_drive_add_drive:
    path:     /save
    defaults: { _controller: DevelopersApiV1Drive:Drive:save }
    methods: [POST]

developers_api_v1_drive_get_list_drive:
    path:     /list
    defaults: { _controller: DevelopersApiV1Drive:Drive:getList }
    methods: [POST]

developers_api_v1_drive_get_find_drive:
    path:     /find
    defaults: { _controller: DevelopersApiV1Drive:Drive:find }
    methods: [POST]

developers_api_v1_drive_download:
    path:     /download
    defaults: { _controller: DevelopersApiV1Drive:Drive:download }
    methods: [POST]