#Events
calendar_event_get:
    path:     /event/get
    defaults: { _controller: Twake\Calendar:Event:get}
    methods: [POST]

calendar_event_save:
    path:     /event/save
    defaults: { _controller: Twake\Calendar:Event:save}
    methods: [POST]

calendar_event_remove:
    path:     /event/remove
    defaults: { _controller: Twake\Calendar:Event:remove}
    methods: [POST]

#Calendars
calendar_calendar_get:
    path:     /calendar/get
    defaults: { _controller: Twake\Calendar:Calendar:get}
    methods: [POST]

calendar_calendar_save:
    path:     /calendar/save
    defaults: { _controller: Twake\Calendar:Calendar:save}
    methods: [POST]

calendar_calendar_remove:
    path:     /calendar/remove
    defaults: { _controller: Twake\Calendar:Calendar:remove}
    methods: [POST]

#Export
calendar_export:
    path:     /export
    defaults: { _controller: Twake\Calendar:Export:export}
    methods: [POST,GET]

calendar_token_export:
    path:     /token_export
    defaults: { _controller: Twake\Calendar:Export:generateToken}
    methods: [POST]
