services:

    app.calendar.event:
        class: Twake\Calendar\Services\CalendarEvent
        arguments: ["@app.twake_doctrine", "@app.websockets", "@app.applications_api", "@app.notifications", "@app.calendar.export"]

    app.calendar.calendar:
        class: Twake\Calendar\Services\CalendarCalendar
        arguments: ["@app.twake_doctrine", "@app.applications_api"]

    app.calendar.export:
        class: Twake\Calendar\Services\CalendarExport
        arguments: ["@app.twake_doctrine"]