
administration_api_group_get_all:
    path: /getgroup
    defaults: { _controller: AdministrationApiGroupBundle:Group:getAllGroup }
    methods: [POST]

administration_api_wp_get_all:
    path: /getwp
    defaults: { _controller: AdministrationApiGroupBundle:Group:getAllWorkspace }
    methods: [POST]

administration_api_group_get_by_name:
  path: /getgroupbyname
  defaults: { _controller: AdministrationApiGroupBundle:Group:getGroupbyname }
  methods: [POST]

administration_api_wp_get_by_name:
  path: /getwpbyname
  defaults: { _controller: AdministrationApiGroupBundle:Group:getWpbyname }
  methods: [POST]

administration_api_user_get_user_by_name:
    path: /getuserbymail
    defaults: { _controller: AdministrationApiGroupBundle:Group:getUserbyMail }
    methods: [POST]