project_create:
    path: workspace/{workspace_id}/project
    methods: [POST]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Project:createProject }
    requirements:
        workspace_id: "[0-9]+"

project_edit:
    path: workspace/{workspace_id}/project/{project_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Project:editProject }
    requirements:
          project_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_delete:
    path: workspace/{workspace_id}/project/{project_id}
    methods: [DELETE]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Project:deleteProject }
    requirements:
          project_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_display:
    path: workspace/{workspace_id}/project/{project_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Project:getProject }
    requirements:
          project_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_all_display:
    path: workspace/{workspace_id}/project/all
    methods: [GET]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Project:getAllProject }
    requirements:
          workspace_id: "[0-9]+"

project_task_display:
    path: workspace/{workspace_id}/project/task/{task_id}
    methods: [GET]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:getTask }
    requirements:
          task_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_task_all_display:
    path: workspace/{workspace_id}/project/{project_id}/task/all
    methods: [GET]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:getAllTask }
    requirements:
          workspace_id: "[0-9]+"
          project_id: "[0-9]+"

project_task_create:
    path: workspace/{workspace_id}/project/task/{project_id}
    methods: [POST]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:createTask }
    requirements:
        workspace_id: "[0-9]+"
        project_id: "[0-9]+"

project_task_edit:
    path: workspace/{workspace_id}/project/task/{task_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:editTask }
    requirements:
          task_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_task_move:
    path: workspace/{workspace_id}/project/task/{task_id}/move
    methods: [POST]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:moveTask }
    requirements:
          task_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_task_delete:
    path: workspace/{workspace_id}/project/{project_id}/task/{task_id}
    methods: [DELETE]
    defaults: { _controller: DevelopersApiV1ProjectBundle:Task:deleteTask }
    requirements:
          task_id: "[0-9]+"
          workspace_id: "[0-9]+"
          project_id: "[0-9]+"

project_list_create:
    path: workspace/{workspace_id}/project/list/{project_id}
    methods: [POST]
    defaults: { _controller: DevelopersApiV1ProjectBundle:List:createList }
    requirements:
        workspace_id: "[0-9]+"
        project_id: "[0-9]+"

project_list_edit:
    path: workspace/{workspace_id}/project/list/{list_id}
    methods: [PUT]
    defaults: { _controller: DevelopersApiV1ProjectBundle:List:editList }
    requirements:
          list_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_list_move:
    path: workspace/{workspace_id}/project/list/{list_id}/move
    methods: [POST]
    defaults: { _controller: DevelopersApiV1ProjectBundle:List:moveList }
    requirements:
          list_id: "[0-9]+"
          workspace_id: "[0-9]+"

project_list_delete:
    path: workspace/{workspace_id}/project/{project_id}/list/{list_id}
    methods: [DELETE]
    defaults: { _controller: DevelopersApiV1ProjectBundle:List:deleteList }
    requirements:
          list_id: "[0-9]+"
          workspace_id: "[0-9]+"
          project_id: "[0-9]+"
