services:

    app.tasks.task:
        class: WebsiteApi\TasksBundle\Services\BoardTask
        arguments: ["@app.twake_doctrine", "@app.websockets", "@app.applications_api", "@app.notifications", "@app.tasks.export"]

    app.tasks.board:
        class: WebsiteApi\TasksBundle\Services\BoardBoard
        arguments: ["@app.twake_doctrine", "@app.applications_api"]

    app.tasks.export:
        class: WebsiteApi\TasksBundle\Services\BoardExport
        arguments: ["@app.twake_doctrine"]