developers_api_v1_core_getInfoFromToken:
    path:     token/{token}
    defaults: { _controller: DevelopersApiV1WorkspacesBundle:Default:getInfoFromToken }
    methods: [GET]
    requirements:
        token: '\d+'
