services:
  api.v1.check:
        class: DevelopersApiV1\CoreBundle\Services\CheckService
        arguments: ["@app.cassandra_doctrine", "@api.v1.access_log"]

  api.v1.api_status:
        class: DevelopersApiV1\CoreBundle\Services\ApiStatus
        arguments: ["@app.cassandra_doctrine"]

  api.v1.access_log:
        class: DevelopersApiV1\CoreBundle\Services\AccessLogSystem
        arguments: ["@app.cassandra_doctrine"]
