services:
  api.v1.check:
        class: DevelopersApiV1\CoreBundle\Services\CheckService
        arguments: ["@doctrine.orm.entity_manager"]

  api.v1.errors_map:
        class: DevelopersApiV1\CoreBundle\Services\ErrorsMap
        arguments: ["@doctrine.orm.entity_manager"]
