services:
  api.v1.check:
        class: DevelopersApiV1\CoreBundle\Services\CheckService
        arguments: ["@doctrine.orm.entity_manager", "@api.v1.access_log"]

  api.v1.api_status:
        class: DevelopersApiV1\CoreBundle\Services\ApiStatus
        arguments: ["@doctrine.orm.entity_manager"]

  api.v1.access_log:
        class: DevelopersApiV1\CoreBundle\Services\AccessLogSystem
        arguments: ["@doctrine.orm.entity_manager"]
