# Apps management

twake_applications_search:
    path:     /app/search
    defaults: { _controller: Twake\Market:Application:search }

twake_applications_find:
    path:     /app/find
    defaults: { _controller: Twake\Market:Application:find }

# Apps API

twake_applications_event:
    path:     /app/api/event
    defaults: { _controller: Twake\Market:ApplicationApi:event }


twake_applications_gettoken:
    path:     /app/api/getToken
    defaults: { _controller: Twake\Market:ApplicationApi:getToken }


# Apps Developers

twake_applications_create:
    path:     /app/create
    defaults: { _controller: Twake\Market:ApplicationDevelopment:create }

twake_applications_remove:
    path:     /app/remove
    defaults: { _controller: Twake\Market:ApplicationDevelopment:remove }

twake_applications_update:
    path:     /app/update
    defaults: { _controller: Twake\Market:ApplicationDevelopment:update }

twake_applications_get_developed:
    path:     /app/get_developed
    defaults: { _controller: Twake\Market:ApplicationDevelopment:getGroupDevelopedApps }

