#Handle all url except special prefixs (see /app/config/routing.yml for more details)
website_public_all:
    path:     /{req}
    defaults: { _controller: WebsitePublicBundle:Default:all }
    requirements:
      req: "^(?!public|dev|js|upload|css|angular).*"