# Drive base

#Old mobile versions
drive_get:
    path:     /drive/get
    defaults: { _controller: Twake\Drive:DriveFile:get}
drive_save:
    path:     /drive/save
    defaults: { _controller: Twake\Drive:DriveFile:save }
drive_get_a_file:
    path:     /drive/find
    defaults: { _controller: Twake\Drive:DriveFile:find }
drive_remove_file:
    path:     /drive/remove
    defaults: { _controller: Twake\Drive:DriveFile:remove }


#Drive v1.2
drive_refractor_get:
    path:     /drive/v2/get
    defaults: { _controller: Twake\Drive:DriveFile:get}

drive_refractor_save:
    path:     /drive/v2/save
    defaults: { _controller: Twake\Drive:DriveFile:save }

drive_refractor_remove:
    path:     /drive/v2/remove
    defaults: { _controller: Twake\Drive:DriveFile:remove }

drive_refractor_get_a_file:
    path:     /drive/v2/find
    defaults: { _controller: Twake\Drive:DriveFile:find }



twake_publicaccess:
    path:     /drive/access/set
    defaults: { _controller: Twake\Drive:DriveFile:set_file_access }
    methods:  [POST]

twake_privateaccess:
    path:     /drive/access/reset
    defaults: { _controller: Twake\Drive:DriveFile:reset_file_access }
    methods:  [POST]

twake_drive_trash_empty:
    path:     /drive/trash/empty
    defaults: { _controller: Twake\Drive:DriveFile:emptyTrash }
    methods: [POST]

drive_send_as_message:
    path:     /drive/send_message
    defaults: { _controller: Twake\Drive:DriveFile:sendAsMessage }

twake_drive_open:
    path:     /drive/open
    defaults: { _controller: Twake\Drive:DriveFile:open }
    methods: [POST]

driveupload_upload:
  path:       /driveupload/upload
  defaults: { _controller: Twake\Drive:Upload:uploadFile }
  methods: [POST]

driveupload_download_alt:
  path:       /drive/download
  defaults: { _controller: Twake\Drive:Download:downloadfile}
  methods: [POST, GET]

driveupload_download:
  path:       /driveupload/download
  defaults: { _controller: Twake\Drive:Download:downloadfile}
  methods: [POST, GET]

driveupload_preprocess:
  path:       /driveupload/preprocess
  defaults: { _controller: Twake\Drive:Upload:Preprocess}
  methods: [POST]
