# Labels

twake_drive_labels_get:
    path:     /labels/get
    defaults: { _controller: TwakeDriveBundle:FilesLabels:get }
    methods: [POST]

twake_drive_labels_update:
    path:     /labels/update
    defaults: { _controller: TwakeDriveBundle:FilesLabels:update }
    methods: [POST]

# Drive

twake_drive_create:
    path:     /create
    defaults: { _controller: TwakeDriveBundle:Files:create }
    methods: [POST]

twake_drive_copy:
    path:     /copy
    defaults: { _controller: TwakeDriveBundle:Files:copy }
    methods: [POST]

twake_drive_list:
    path:     /list
    defaults: { _controller: TwakeDriveBundle:Files:list }
    methods: [POST]

twake_drive_list_last_used:
    path: /listLastUsed
    defaults: { _controller: TwakeDriveBundle:Files:listLastUsed }
    methods: [POST]

twake_drive_preview:
    path:     /preview
    defaults: { _controller: TwakeDriveBundle:Files:preview }
    methods: [GET]

twake_drive_search:
    path:     /search
    defaults: { _controller: TwakeDriveBundle:Files:search }
    methods: [POST]

twake_drive_upload:
    path:     /upload
    defaults: { _controller: TwakeDriveBundle:Files:upload }
    methods: [POST]

twake_drive_upload:
    path:     /download
    defaults: { _controller: TwakeDriveBundle:Files:download }
    methods: [GET]

twake_drive_move:
    path:     /move
    defaults: { _controller: TwakeDriveBundle:Files:move }
    methods: [POST]

twake_drive_copy:
    path:     /copy
    defaults: { _controller: TwakeDriveBundle:Files:copy }
    methods: [POST]

twake_drive_rename:
    path:     /rename
    defaults: { _controller: TwakeDriveBundle:Files:rename }
    methods: [POST]

twake_drive_getshared:
    path:     /getShared
    defaults: { _controller: TwakeDriveBundle:Files:getShared }
    methods: [POST]

twake_drive_share:
    path:     /share
    defaults: { _controller: TwakeDriveBundle:Files:share }
    methods: [POST]

twake_drive_unshare:
    path:     /unshare
    defaults: { _controller: TwakeDriveBundle:Files:unshare }
    methods: [POST]

twake_drive_content_get_details:
    path:     /details
    defaults: { _controller: TwakeDriveBundle:Files:getDetails }
    methods: [POST]

twake_drive_content_get:
    path:     /content/get
    defaults: { _controller: TwakeDriveBundle:Files:getContent }
    methods: [POST]

twake_drive_content_set:
    path:     /content/set
    defaults: { _controller: TwakeDriveBundle:Files:setContent }
    methods: [POST]

twake_drive_open:
    path:     /open
    defaults: { _controller: TwakeDriveBundle:Files:open }
    methods: [POST]

twake_drive_getAppFiles:
    path:     /getAppFiles
    defaults: { _controller: TwakeDriveBundle:Files:getFilesFromApp }
    methods: [POST]

twake_drive_getDriveFileVersion:
    path:     /getDriveFileVersions
    defaults: { _controller: TwakeDriveBundle:Files:getDriveFileVersions }
    methods: [POST]


# Trash

twake_drive_delete:
    path:     /delete
    defaults: { _controller: TwakeDriveBundle:Files:delete }
    methods: [POST]

twake_drive_trash_restore:
    path:     /trash/restore
    defaults: { _controller: TwakeDriveBundle:Files:restoreTrash }
    methods: [POST]

twake_drive_trash_empty:
    path:     /trash/empty
    defaults: { _controller: TwakeDriveBundle:Files:emptyTrash }
    methods: [POST]

# UsersToNotify

twake_drive_get_users_to_notify:
    path:     /users_to_notify/get
    defaults: { _controller: TwakeDriveBundle:UsersToNotify:getUsers }

twake_drive_set_users_to_notify:
    path:     /users_to_notify/set
    defaults: { _controller: TwakeDriveBundle:UsersToNotify:setUsers }
    methods: [POST]

twake_drive_post_gdrive_notification:
    path:     /users_to_notify/post_gdrive_notification
    defaults: { _controller: TwakeDriveBundle:UsersToNotify:postGDriveNotification }

# External drive handler

twake_drive_add_google_drive:
    path:     /gdrive/add
    defaults: { _controller: TwakeDriveBundle:ExternalFiles:addNewExternalDrive }

twake_drive_google_drive_response:
    path:     /gdrive/fetchAccessTokenWithAuthCode
    defaults: { _controller: TwakeDriveBundle:ExternalFiles:fetchAccessTokenWithAuthCode }

twake_drive_get_external_drives:
    path:     /gdrive/getExternalDrives
    defaults: { _controller: TwakeDriveBundle:ExternalFiles:getExternalDrives }
    
# Activity

drive_activities_create:
    path: /driveActivities/create
    defaults: { _controller: TwakeDriveBundle:DriveActivity:create }
    methods: [POST]

drive_activities_get:
    path: /driveActivities/get
    defaults: { _controller: TwakeDriveBundle:DriveActivity:get }
    methods: [POST]

drive_activities_readAll:
    path: /driveActivities/readAll
    defaults: { _controller: TwakeDriveBundle:DriveActivity:readAll }
    methods: [POST]

drive_activities_readOne:
    path: /driveActivities/readOne
    defaults: { _controller: TwakeDriveBundle:DriveActivity:readOne}
    methods: [POST]

drive_activities_delete:
    path: /driveActivities/delete
    defaults: { _controller: TwakeDriveBundle:DriveActivity:delete}
    methods: [POST]

drive_activities_getActivityToDisplay:
    path: /driveActivities/getActivityToDisplay
    defaults: { _controller: TwakeDriveBundle:DriveActivity:getActivityToDisplay}
    methods: [POST]
