services:

    app.drive.FileSystem:
        class: WebsiteApi\DriveBundle\Services\DriveFileSystem
        arguments: ["@doctrine.orm.entity_manager", %kernel.root_dir%, "@app.drive.Labels", "%DRIVE_SALT%","@app.pricing_plan", "@app.drive.Preview", '@app.pusher','@website_api_market.applications']

    app.drive.FileSystem_:
        class: WebsiteApi\DriveBundle\Services\DriveFileSystemGDrive
        arguments: ["@doctrine.orm.entity_manager", "@app.drive.GDriveApiSystem", '@app.pusher',"@circle.restclient", '@app.drive.FileSystem_']

    app.drive.ExternalDriveDataCacheSystem:
        class: WebsiteApi\DriveBundle\Services\ExternalDriveDataCacheSystem
        arguments: ["@doctrine.orm.entity_manager"]

    app.drive.GDriveApiSystem:
        class: WebsiteApi\DriveBundle\Services\GDriveApiSystem
        arguments: ["@doctrine.orm.entity_manager", "@circle.restclient", "@app.drive.ExternalDriveDataCacheSystem", '@app.pusher']

    app.drive.SmartFolders:
        class: WebsiteApi\DriveBundle\Services\DriveSmartFolders
        arguments: ["@doctrine.orm.entity_manager"]

    app.drive.Labels:
        class: WebsiteApi\DriveBundle\Services\DriveLabels
        arguments: ["@doctrine.orm.entity_manager"]

    app.drive.Preview:
      class: WebsiteApi\DriveBundle\Services\DrivePreview
      arguments: ["@doctrine.orm.entity_manager"]

    drive.topic:
        class: WebsiteApi\DriveBundle\Topic\DriveTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: []