services:

    app.drive.FileSystem:
        class: WebsiteApi\DriveBundle\Services\DriveFileSystem
        arguments: ["@doctrine.orm.entity_manager", %kernel.root_dir%, "@app.drive.Labels", "%DRIVE_SALT%","@app.pricing_plan", "@app.drive.Preview", '@app.pusher','@website_api_market.applications']

    app.drive.SmartFolders:
        class: WebsiteApi\DriveBundle\Services\DriveSmartFolders
        arguments: ["@doctrine.orm.entity_manager"]

    app.drive.Labels:
        class: WebsiteApi\DriveBundle\Services\DriveLabels
        arguments: ["@doctrine.orm.entity_manager"]

    app.drive.Preview:
      class: WebsiteApi\DriveBundle\Services\DrivePreview
      arguments: ["@doctrine.orm.entity_manager"]

    drive.topic:
        class: WebsiteApi\DriveBundle\Topic\DriveTopic
        tags:
            - { name: gos_web_socket.topic }
        arguments: []