services:

    app.drive.preview:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\DrivePreview
      arguments: ["@app.twake_doctrine"]

    app.drive:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\DriveFileSystem
      arguments: ["@app.twake_doctrine", "@app.applications_api", "@app.websockets"]

    driveupload.storemanager:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\Storage\StorageManager
      arguments: [%local%, %aws%, %openstack%, %kernel.root_dir%, "@app.drive.preview","@app.twake_doctrine"]

    driveupload.download:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\DownloadFile
      arguments: ["@driveupload.resumable", "@app.twake_doctrine","@driveupload.storemanager", %DRIVE_SALT%, "@app.drive.old.adapter_selector"]

    driveupload.resumable:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\Resumable\Resumable
      arguments: ["@app.twake_doctrine","@driveupload.storemanager", "@app.drive", %drive_previews_tmp_folder%, %drive_tmp_folder%, %DRIVE_SALT%]

    driveupload.upload:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\UploadFile
      arguments: ["@driveupload.resumable"]

    ### OLD

    app.drive.old.adapter_selector:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\OldFileSystem\DriveAdapterSelector
      arguments: [%aws%, %openstack%, "@app.drive.old.AWS_FileSystem", "@app.drive.old.OpenStack_FileSystem"]

    app.drive.old.OpenStack_FileSystem:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\OldFileSystem\Adapter_OpenStack_DriveFileSystem
      arguments: [%openstack%, %kernel.root_dir%, %DRIVE_SALT%]

    app.drive.old.AWS_FileSystem:
      lazy: true
      class: WebsiteApi\DriveBundle\Services\OldFileSystem\Adapter_AWS_DriveFileSystem
      arguments: [%aws%, %kernel.root_dir%, %DRIVE_SALT%]
