# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend tests

on:
  push:
    branches: [master, "feature/*"]
  pull_request:
    branches: [master, "feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd twake && mv docker-compose.yml.dist.tests docker-compose.yml
      - run: cd twake && docker-compose up -d
      - run: cd twake && docker-compose exec -T php php composer.phar install
      - run: cd twake && docker-compose exec -T php php bin/console twake:schema:update #Test if scylla is live
      - run: cd twake && docker-compose exec -T php php bin/console twake:mapping #Test if es is live
      - run: cd twake && docker-compose exec -T php php bin/console twake:init #Test in we can do things
