name: frontend-build

on:
  push:
    branches: [master, "feature/*"]
    paths:
      - "twake/frontend/**"
  pull_request:
    branches: [master, "feature/*"]
    paths:
      - "twake/frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: cd twake/frontend/ && yarn install
      - run: cd twake/frontend/ && cp src/app/environment/environment.ts.dist src/app/environment/environment.ts
      - run: cd twake/frontend/ && yarn build
