name: update-saas-backend

# Deploy backend only if push on "main"
on:
  push:
    branches: [main]
    paths:
      - "twake/docker/**"
      - "twake/backend/**"
      - ".github/workflows/**"

jobs:
  deploy-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: twaketech/twake-php
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: twake
          buildoptions: "-t twaketech/twake-php -f docker/twake-php/Dockerfile"

  deploy-websockets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: twaketech/twake-websockets
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: twake
          buildoptions: "-t twaketech/twake-websockets -f docker/twake-websockets/Dockerfile"
